## Analisis de base de datos sintetica generada a partir del contexto de la empresa Sigma Foods (2026)

In [127]:
import pandas as pd
import numpy as np

## Cargar 5 CSVs con la información de los candidatos

In [128]:
df_candidate = pd.read_csv("candidate_profile.csv",encoding='utf-8-sig')
df_dictionary = pd.read_csv("data_dictionary.csv",encoding='utf-8-sig')
df_demographics = pd.read_csv("demographics.csv",encoding='utf-8-sig')
df_plantilla = pd.read_csv("plantilla_global.csv",encoding='utf-8-sig')
df_succession = pd.read_csv("succession.csv",encoding='utf-8-sig')

df_candidate.info()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 60 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Employee ID                     50000 non-null  str
 1   Full Name                       50000 non-null  str
 2   Second Surname                  50000 non-null  str
 3   Optional Phone                  50000 non-null  int64
 4   Postal Code                     50000 non-null  int64
 5   Country                         50000 non-null  str
 6   State                           50000 non-null  str
 7   Municipality                    50000 non-null  str
 8   Date of Birth                   50000 non-null  str
 9   Nationality                     50000 non-null  str
 10  Civil Status                    50000 non-null  str
 11  Native Language                 50000 non-null  str
 12  Profile Visibility              50000 non-null  str
 13  Relocation Availability         50000 non-null  str
 14  Education_Degree_1              50000 non-null  str
 15  Education_Institution_1         50000 non-null  str
 16  Education_Field_1               50000 non-null  str
 17  Education_Year_1                50000 non-null  int64
 18  Education_Degree_2              50000 non-null  str
 19  Education_Institution_2         50000 non-null  str
 20  Education_Field_2               50000 non-null  str
 21  Education_Year_2                50000 non-null  int64
 22  PrevJob_Company_1               50000 non-null  str
 23  PrevJob_Title_1                 50000 non-null  str
 24  PrevJob_Start_1                 50000 non-null  str
 25  PrevJob_End_1                   50000 non-null  str
 26  PrevJob_Company_2               50000 non-null  str
 27  PrevJob_Title_2                 50000 non-null  str
 28  PrevJob_Start_2                 50000 non-null  str
 29  PrevJob_End_2                   50000 non-null  str
 30  Area_of_Interest_1              50000 non-null  str
 31  Area_of_Interest_2              50000 non-null  str
 32  Certification_1                 50000 non-null  str
 33  Certification_Year_1            50000 non-null  int64
 34  Certification_2                 50000 non-null  str
 35  Certification_Year_2            50000 non-null  int64
 36  Language_1                      50000 non-null  str
 37  Language_1_Level                50000 non-null  str
 38  Language_2                      50000 non-null  str
 39  Language_2_Level                50000 non-null  str
 40  Course_1                        50000 non-null  str
 41  Course_Year_1                   50000 non-null  int64
 42  Course_2                        50000 non-null  str
 43  Course_Year_2                   50000 non-null  int64
 44  Leadership_Vision               50000 non-null  int64
 45  Leadership_Influence            50000 non-null  int64
 46  Leadership_Decision_Making      50000 non-null  int64
 47  Functional_Execution            50000 non-null  int64
 48  Functional_Innovation           50000 non-null  int64
 49  Functional_Results_Orientation  50000 non-null  int64
 50  Cultural_Collaboration          50000 non-null  int64
 51  Cultural_Integrity              50000 non-null  int64
 52  Cultural_Customer_Focus         50000 non-null  int64
 53  Communication                   50000 non-null  int64
 54  Adaptability                    50000 non-null  int64
 55  Learning_Agility                50000 non-null  int64
 56  Score_Liderazgo                 50000 non-null  float64
 57  Score_Funcional                 50000 non-null  float64
 58  Score_Cultural                  50000 non-null  float64
 59  Score_General                   50000 non-null  float64
dtypes: float64(4), int64(20), str(36)
memory usage: 22.9 MB

In [129]:
df_candidate.dtypes

Employee ID                           str
Full Name                             str
Second Surname                        str
Optional Phone                      int64
Postal Code                         int64
Country                               str
State                                 str
Municipality                          str
Date of Birth                         str
Nationality                           str
Civil Status                          str
Native Language                       str
Profile Visibility                    str
Relocation Availability               str
Education_Degree_1                    str
Education_Institution_1               str
Education_Field_1                     str
Education_Year_1                    int64
Education_Degree_2                    str
Education_Institution_2               str
Education_Field_2                     str
Education_Year_2                    int64
PrevJob_Company_1                     str
PrevJob_Title_1                       str
PrevJob_Start_1                       str
PrevJob_End_1                         str
PrevJob_Company_2                     str
PrevJob_Title_2                       str
PrevJob_Start_2                       str
PrevJob_End_2                         str
Area_of_Interest_1                    str
Area_of_Interest_2                    str
Certification_1                       str
Certification_Year_1                int64
Certification_2                       str
Certification_Year_2                int64
Language_1                            str
Language_1_Level                      str
Language_2                            str
Language_2_Level                      str
Course_1                              str
Course_Year_1                       int64
Course_2                              str
Course_Year_2                       int64
Leadership_Vision                   int64
Leadership_Influence                int64
Leadership_Decision_Making          int64
Functional_Execution                int64
Functional_Innovation               int64
Functional_Results_Orientation      int64
Cultural_Collaboration              int64
Cultural_Integrity                  int64
Cultural_Customer_Focus             int64
Communication                       int64
Adaptability                        int64
Learning_Agility                    int64
Score_Liderazgo                   float64
Score_Funcional                   float64
Score_Cultural                    float64
Score_General                     float64
dtype: object

## Se verificaron las columnas y los nombres de indice para cada dataset

In [130]:
#Cambiamos nombre de columna "NIP -> Employee ID" para homogenizar indices
df_plantilla = df_plantilla.rename(columns={'NIP': 'Employee ID'})

#Observamos las columnas y conteo su respectivo conteo
print("Columnas de df_plantilla:")
print(list(df_plantilla.columns))
print("Columnas:",len(df_plantilla.columns))
print()
print("Columnas de df_demographics:")
print(list(df_demographics.columns))
print("Columnas:",len(df_demographics.columns))
print()
print("Columnas de df_candidate:")
print(list(df_candidate.columns))
print("Columnas:",len(df_candidate.columns))

#Después aplicas el index para cada csv
df_plantilla = df_plantilla.set_index('Employee ID')
df_demographics = df_demographics.set_index('Employee ID')
df_candidate = df_candidate.set_index('Employee ID')

print()
#Comprobamos los indices para cada csv
print()
print("Índice de df_plantilla:", df_plantilla.index.name)
print("Índice de df_demographics:", df_demographics.index.name)
print("Índice de df_candidate:", df_candidate.index.name)

Columnas de df_plantilla:
['Employee ID', 'NOMBRE', 'GENERO', 'F.NACIMIENTO', 'F.I.ALFA', 'F.I.SIGMA', 'DESCRIP. DIRECCION', 'DESCRIP. GERENCIA', 'DESCRIP. AREA', 'DESCRIP. DEPARTAMENTO', 'DESCRIP. SITE', 'Country', 'NIVEL', 'IPE', 'SEGMENTO P', 'EXECUTIVE', 'DIVISION', 'DESCRIP. FUNCION', 'SUBTIPO', 'GRUPO', 'SUELDO SAP', 'SDO MENSUALIZAD', 'MONED', 'TIPO CAM', 'SDO PESOS MXN', 'Sueldo USD', 'BONOS Y COM ORI', 'SDO BYC MXN', 'POSICI']
Columnas: 29

Columnas de df_demographics:
['Employee ID', 'Employee Name', 'Gender', 'Date of Birth', 'Type of Employee', 'Employee Position Type', 'Date of Entry to Alfa', 'Date of Entry to Sigma', 'Headcount', 'Age', 'Tenure (Years) Alfa', 'Tenure (Years) Sigma', 'Age Band', 'Tenure Band']
Columnas: 14

Columnas de df_candidate:
['Employee ID', 'Full Name', 'Second Surname', 'Optional Phone', 'Postal Code', 'Country', 'State', 'Municipality', 'Date of Birth', 'Nationality', 'Civil Status', 'Native Language', 'Profile Visibility', 'Relocation Availability', 'Education_Degree_1', 'Education_Institution_1', 'Education_Field_1', 'Education_Year_1', 'Education_Degree_2', 'Education_Institution_2', 'Education_Field_2', 'Education_Year_2', 'PrevJob_Company_1', 'PrevJob_Title_1', 'PrevJob_Start_1', 'PrevJob_End_1', 'PrevJob_Company_2', 'PrevJob_Title_2', 'PrevJob_Start_2', 'PrevJob_End_2', 'Area_of_Interest_1', 'Area_of_Interest_2', 'Certification_1', 'Certification_Year_1', 'Certification_2', 'Certification_Year_2', 'Language_1', 'Language_1_Level', 'Language_2', 'Language_2_Level', 'Course_1', 'Course_Year_1', 'Course_2', 'Course_Year_2', 'Leadership_Vision', 'Leadership_Influence', 'Leadership_Decision_Making', 'Functional_Execution', 'Functional_Innovation', 'Functional_Results_Orientation', 'Cultural_Collaboration', 'Cultural_Integrity', 'Cultural_Customer_Focus', 'Communication', 'Adaptability', 'Learning_Agility', 'Score_Liderazgo', 'Score_Funcional', 'Score_Cultural', 'Score_General']
Columnas: 60


Índice de df_plantilla: Employee ID
Índice de df_demographics: Employee ID
Índice de df_candidate: Employee ID

In [131]:
print("Índice de df_succession:", df_succession.index.name)
print("Primeras filas:")
df_succession.head(3)

Índice de df_succession: None
Primeras filas:

,Position_Code,Job Title,Level,Position_Business_Unit,Incumbent_Id,Incumbent Full Name,Incumbent_OU,Incumbent_Date_Of_Birth,Edad,Nominee_User_ID,Full Name Sucesor,Nominee_Gender,Nominee_Date_of_Birth,Nominee_Position_Title,Nominee_Position_Code,Nominee_Business_Unit,Nomination_Readiness,Nomination_Date,Nominator_User_ID
0,POS13178,Manager Operaciones,N1,Dirección de Operaciones,NIP119205,Elena Flores,Área CDMX,1983-10-25,41,NIP144127,Óscar Luna,M,1973-12-22,Analyst Logística,POS28384,Dirección de Operaciones,Short Term,2025-07-26,NIP144680
1,POS12049,Manager Logística,N1,Dirección de RH,NIP106565,Ana Chavez,Área Centro,1992-02-18,33,NIP122110,Cristina Ramos,F,1998-06-29,Analyst Ventas,POS27005,Dirección Legal,Long Term,2025-01-19,NIP104710
2,POS12956,Manager Ventas,N2,Dirección de Marketing,NIP109751,Enrique Ortiz,Área Centro,1990-07-19,34,NIP103274,Héctor Villalobos,M,1992-11-10,Analyst Logística,POS21161,Dirección de Tecnología,Short Term,2024-07-18,NIP106109

 Se generara un indice significativo para el archivo "succession.csv" dado a que los NIP que funcionaban como identificadores únicos en el resto de archivos csv, en este en particular se repiten más de una ocasión debido a que un empleado puede ser adecuado para multiples vacantes

In [132]:
# Paso 1 — Crear la columna Nomination_ID al inicio del DataFrame
df_succession.insert(0, 'Nomination ID', range(1, len(df_succession) + 1))

# Paso 2 — Establecerla como índice
df_succession = df_succession.set_index('Nomination ID')

# Paso 3 — Verificar resultado
print(f" Succession → índice: {df_succession.index.name}")
print(f" Rango: {df_succession.index.min()} al {df_succession.index.max()}")
df_succession.sample(3)

 Succession → índice: Nomination ID
 Rango: 1 al 38200

,Position_Code,Job Title,Level,Position_Business_Unit,Incumbent_Id,Incumbent Full Name,Incumbent_OU,Incumbent_Date_Of_Birth,Edad,Nominee_User_ID,Full Name Sucesor,Nominee_Gender,Nominee_Date_of_Birth,Nominee_Position_Title,Nominee_Position_Code,Nominee_Business_Unit,Nomination_Readiness,Nomination_Date,Nominator_User_ID
Nomination ID,,,,,,,,,,,,,,,,,,,
34714,POS10455,Manager Marketing,N2,Dirección de RH,NIP129428,Elena Ramos,Área Centro,1971-02-21,54,NIP146567,Verónica Ibarra,F,1988-12-31,Analyst Tecnología,POS20867,Dirección de RH,Medium Term,2025-08-15,NIP136696
24239,POS21878,Manager Ventas,N1,Dirección de Operaciones,NIP108050,Adriana Cruz,Área Centro,1988-12-12,36,NIP108253,Paulina Cabrera,F,1969-08-18,Analyst Logística,POS25478,Dirección de Operaciones,Short Term,2025-03-09,NIP113044
21637,POS21599,Manager Ventas,N3,Dirección Comercial,NIP142046,Verónica Mendoza,Área Bajío,1974-11-24,50,NIP146307,Fernando Medina,M,1968-06-26,Analyst Logística,POS22105,Dirección de Tecnología,Short Term,2025-06-02,NIP142686

## Seleccionar subconjuntos para verificar si los datos de los empleados tienen sentido

In [133]:
#Selecciona un empleado específico por su Employee ID y solo las columnas que nos interesan para el proyecto

df_plantilla.loc['NIP100018',['NOMBRE', 'Country', 'DIVISION', 'SEGMENTO P', 'MONED', 'SDO MENSUALIZAD']]

NOMBRE             Patricia Martínez
Country                       México
DIVISION                 Corporativo
SEGMENTO P                DIRECTORES
MONED                            MXN
SDO MENSUALIZAD             24118.83
Name: NIP100018, dtype: object

In [134]:
# Filas del 10 al 14, primeras 5 columnas
df_demographics.iloc[10:15, 0:5]

,Employee Name,Gender,Date of Birth,Type of Employee,Employee Position Type
Employee ID,,,,,
NIP100011,Patricia Rivera,Female,1980-06-20,Administrator,Contract
NIP100012,Walter Rodríguez,Male,1983-12-08,Operator,Contract
NIP100013,Finn Becker,Male,1996-06-25,Operator,Permanent
NIP100014,Miguel García,Male,1985-01-07,Administrator,Contract
NIP100015,Ricardo Sánchez,Male,1969-06-09,Operator,Temporary

In [135]:
# PROPÓSITO: Identificar candidatos con alto potencial de liderazgo para el proceso de sucesión ejecutiva —> caso de uso directo del proyecto

df_candidate[df_candidate['Score_General'] > 80][
    ['Full Name', 'Country', 'Score_Liderazgo', 'Score_Funcional', 'Score_Cultural', 'Score_General']
].head(10)

,Full Name,Country,Score_Liderazgo,Score_Funcional,Score_Cultural,Score_General
Employee ID,,,,,,
NIP102815,Manuel Flores,México,81.7,82.0,85.0,80.6
NIP114132,Jorge Rodríguez,México,87.7,86.0,75.0,82.1
NIP114496,Marcela Rivera,México,80.3,76.7,86.3,81.4
NIP119312,Manuel Sánchez,México,76.7,81.7,86.3,80.9
NIP121860,Alejandra Rivera,México,92.0,90.7,64.3,80.7
NIP127327,Gabriel Ortiz,México,84.3,86.7,76.0,80.1

## Estandarización de nombres en las 4 Tablas:

## Plantilla Global

In [136]:
df_plantilla.index.name = 'employee_id'

df_plantilla = df_plantilla.rename(columns={
    'NOMBRE'              : 'full_name',
    'GENERO'              : 'gender',
    'F.NACIMIENTO'        : 'date_of_birth',
    'F.I.ALFA'            : 'date_of_entry_alfa',
    'F.I.SIGMA'           : 'date_of_entry_sigma',
    'DESCRIP. DIRECCION'  : 'direction',
    'DESCRIP. GERENCIA'   : 'management',
    'DESCRIP. AREA'       : 'area',
    'DESCRIP. DEPARTAMENTO': 'department',
    'DESCRIP. SITE'       : 'site',
    'Country'             : 'country',
    'NIVEL'               : 'level',
    'IPE'                 : 'ipe',
    'SEGMENTO P'          : 'segment',
    'EXECUTIVE'           : 'is_executive',
    'DIVISION'            : 'division',
    'DESCRIP. FUNCION'    : 'job_function',
    'SUBTIPO'             : 'contract_type',
    'GRUPO'               : 'employee_group',
    'SUELDO SAP'          : 'salary_sap',
    'SDO MENSUALIZAD'     : 'monthly_salary',
    'MONED'               : 'currency',
    'TIPO CAM'            : 'exchange_rate',
    'SDO PESOS MXN'       : 'monthly_salary_mxn',
    'Sueldo USD'          : 'monthly_salary_usd',
    'BONOS Y COM ORI'     : 'bonuses_original',
    'SDO BYC MXN'         : 'total_compensation_mxn',
    'POSICI'              : 'comp_ratio',
})

print('Plantilla Global estandarizada')
print(f'Columnas finales: {list(df_plantilla.columns)}')

Plantilla Global estandarizada
Columnas finales: ['full_name', 'gender', 'date_of_birth', 'date_of_entry_alfa', 'date_of_entry_sigma', 'direction', 'management', 'area', 'department', 'site', 'country', 'level', 'ipe', 'segment', 'is_executive', 'division', 'job_function', 'contract_type', 'employee_group', 'salary_sap', 'monthly_salary', 'currency', 'exchange_rate', 'monthly_salary_mxn', 'monthly_salary_usd', 'bonuses_original', 'total_compensation_mxn', 'comp_ratio']

## Demographics

In [137]:
df_demographics.index.name = 'employee_id'

df_demographics = df_demographics.rename(columns={
    'Employee Name'         : 'full_name',
    'Gender'                : 'gender',
    'Date of Birth'         : 'date_of_birth',
    'Type of Employee'      : 'employee_type',
    'Employee Position Type': 'position_type',
    'Date of Entry to Alfa' : 'date_of_entry_alfa',
    'Date of Entry to Sigma': 'date_of_entry_sigma',
    'Headcount'             : 'headcount',
    'Age'                   : 'age',
    'Tenure (Years) Alfa'   : 'tenure_alfa_years',
    'Tenure (Years) Sigma'  : 'tenure_sigma_years',
    'Age Band'              : 'age_band',
    'Tenure Band'           : 'tenure_band',
})

print('Demographics estandarizado')
print(f'Columnas finales: {list(df_demographics.columns)}')

Demographics estandarizado
Columnas finales: ['full_name', 'gender', 'date_of_birth', 'employee_type', 'position_type', 'date_of_entry_alfa', 'date_of_entry_sigma', 'headcount', 'age', 'tenure_alfa_years', 'tenure_sigma_years', 'age_band', 'tenure_band']

## Candidate Profile

In [138]:
df_candidate.index.name = 'employee_id'

df_candidate = df_candidate.rename(columns={
    'Full Name'                    : 'full_name',
    'Second Surname'               : 'second_surname',
    'Optional Phone'               : 'phone',
    'Postal Code'                  : 'postal_code',
    'Country'                      : 'country',
    'State'                        : 'state',
    'Municipality'                 : 'municipality',
    'Date of Birth'                : 'date_of_birth',
    'Nationality'                  : 'nationality',
    'Civil Status'                 : 'civil_status',
    'Native Language'              : 'native_language',
    'Profile Visibility'           : 'profile_visibility',
    'Relocation Availability'      : 'relocation_available',
    'Education_Degree_1'           : 'education_degree_1',
    'Education_Institution_1'      : 'education_institution_1',
    'Education_Field_1'            : 'education_field_1',
    'Education_Year_1'             : 'education_year_1',
    'Education_Degree_2'           : 'education_degree_2',
    'Education_Institution_2'      : 'education_institution_2',
    'Education_Field_2'            : 'education_field_2',
    'Education_Year_2'             : 'education_year_2',
    'PrevJob_Company_1'            : 'prev_company_1',
    'PrevJob_Title_1'              : 'prev_title_1',
    'PrevJob_Start_1'              : 'prev_start_1',
    'PrevJob_End_1'                : 'prev_end_1',
    'PrevJob_Company_2'            : 'prev_company_2',
    'PrevJob_Title_2'              : 'prev_title_2',
    'PrevJob_Start_2'              : 'prev_start_2',
    'PrevJob_End_2'                : 'prev_end_2',
    'Area_of_Interest_1'           : 'interest_area_1',
    'Area_of_Interest_2'           : 'interest_area_2',
    'Certification_1'              : 'certification_1',
    'Certification_Year_1'         : 'certification_year_1',
    'Certification_2'              : 'certification_2',
    'Certification_Year_2'         : 'certification_year_2',
    'Language_1'                   : 'language_1',
    'Language_1_Level'             : 'language_1_level',
    'Language_2'                   : 'language_2',
    'Language_2_Level'             : 'language_2_level',
    'Course_1'                     : 'course_1',
    'Course_Year_1'                : 'course_year_1',
    'Course_2'                     : 'course_2',
    'Course_Year_2'                : 'course_year_2',
    'Leadership_Vision'            : 'leadership_vision',
    'Leadership_Influence'         : 'leadership_influence',
    'Leadership_Decision_Making'   : 'leadership_decision_making',
    'Functional_Execution'         : 'functional_execution',
    'Functional_Innovation'        : 'functional_innovation',
    'Functional_Results_Orientation': 'functional_results_orientation',
    'Cultural_Collaboration'       : 'cultural_collaboration',
    'Cultural_Integrity'           : 'cultural_integrity',
    'Cultural_Customer_Focus'      : 'cultural_customer_focus',
    'Communication'                : 'communication',
    'Adaptability'                 : 'adaptability',
    'Learning_Agility'             : 'learning_agility',
    'Score_Liderazgo'              : 'score_leadership',
    'Score_Funcional'              : 'score_functional',
    'Score_Cultural'               : 'score_cultural',
    'Score_General'                : 'score_overall',
})

print('Candidate Profile estandarizado')
print(f'Columnas finales: {list(df_candidate.columns)}')

Candidate Profile estandarizado
Columnas finales: ['full_name', 'second_surname', 'phone', 'postal_code', 'country', 'state', 'municipality', 'date_of_birth', 'nationality', 'civil_status', 'native_language', 'profile_visibility', 'relocation_available', 'education_degree_1', 'education_institution_1', 'education_field_1', 'education_year_1', 'education_degree_2', 'education_institution_2', 'education_field_2', 'education_year_2', 'prev_company_1', 'prev_title_1', 'prev_start_1', 'prev_end_1', 'prev_company_2', 'prev_title_2', 'prev_start_2', 'prev_end_2', 'interest_area_1', 'interest_area_2', 'certification_1', 'certification_year_1', 'certification_2', 'certification_year_2', 'language_1', 'language_1_level', 'language_2', 'language_2_level', 'course_1', 'course_year_1', 'course_2', 'course_year_2', 'leadership_vision', 'leadership_influence', 'leadership_decision_making', 'functional_execution', 'functional_innovation', 'functional_results_orientation', 'cultural_collaboration', 'cultural_integrity', 'cultural_customer_focus', 'communication', 'adaptability', 'learning_agility', 'score_leadership', 'score_functional', 'score_cultural', 'score_overall']

## Succession

In [139]:
df_succession.index.name = 'nomination_id'

df_succession = df_succession.rename(columns={
    'Position_Code'          : 'position_code',
    'Job Title'              : 'job_title',
    'Level'                  : 'level',
    'Position_Business_Unit' : 'business_unit',
    'Incumbent_Id'           : 'incumbent_id',
    'Incumbent Full Name'    : 'incumbent_name',
    'Incumbent_OU'           : 'incumbent_ou',
    'Incumbent_Date_Of_Birth': 'incumbent_dob',
    'Edad'                   : 'incumbent_age',
    'Nominee_User_ID'        : 'nominee_id',
    'Full Name Sucesor'      : 'nominee_name',
    'Nominee_Gender'         : 'nominee_gender',
    'Nominee_Date_of_Birth'  : 'nominee_dob',
    'Nominee_Position_Title' : 'nominee_position_title',
    'Nominee_Position_Code'  : 'nominee_position_code',
    'Nominee_Business_Unit'  : 'nominee_business_unit',
    'Nomination_Readiness'   : 'readiness',
    'Nomination_Date'        : 'nomination_date',
    'Nominator_User_ID'      : 'nominator_id',
})

print('Succession estandarizado')
print(f'Columnas finales: {list(df_succession.columns)}')

Succession estandarizado
Columnas finales: ['position_code', 'job_title', 'level', 'business_unit', 'incumbent_id', 'incumbent_name', 'incumbent_ou', 'incumbent_dob', 'incumbent_age', 'nominee_id', 'nominee_name', 'nominee_gender', 'nominee_dob', 'nominee_position_title', 'nominee_position_code', 'nominee_business_unit', 'readiness', 'nomination_date', 'nominator_id']

## Información de la Plantilla Global de Sigma Foods (Datos sintéticos)

In [140]:
df_plantilla.info()

<class 'pandas.DataFrame'>
Index: 50000 entries, NIP100001 to NIP150000
Data columns (total 28 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   full_name               50000 non-null  str
 1   gender                  50000 non-null  str
 2   date_of_birth           50000 non-null  str
 3   date_of_entry_alfa      50000 non-null  str
 4   date_of_entry_sigma     50000 non-null  str
 5   direction               50000 non-null  str
 6   management              50000 non-null  str
 7   area                    50000 non-null  str
 8   department              50000 non-null  str
 9   site                    50000 non-null  str
 10  country                 50000 non-null  str
 11  level                   50000 non-null  str
 12  ipe                     50000 non-null  int64
 13  segment                 50000 non-null  str
 14  is_executive            50000 non-null  str
 15  division                50000 non-null  str
 16  job_function            50000 non-null  str
 17  contract_type           50000 non-null  str
 18  employee_group          50000 non-null  str
 19  salary_sap              50000 non-null  float64
 20  monthly_salary          50000 non-null  float64
 21  currency                50000 non-null  str
 22  exchange_rate           50000 non-null  float64
 23  monthly_salary_mxn      50000 non-null  float64
 24  monthly_salary_usd      50000 non-null  float64
 25  bonuses_original        50000 non-null  float64
 26  total_compensation_mxn  50000 non-null  float64
 27  comp_ratio              50000 non-null  float64
dtypes: float64(8), int64(1), str(19)
memory usage: 12.1+ MB

## Conteo de empleados por región

In [141]:
# Distribución geográfica de empleados por región
distribucion_geografica = df_plantilla.groupby('country').agg(
    total_empleados=('full_name', 'count'),
).reset_index()

# Agregar porcentaje
distribucion_geografica['porcentaje'] = (
    distribucion_geografica['total_empleados'] / 
    distribucion_geografica['total_empleados'].sum() * 100
).round(1).astype(str) + '%'

# Ordenar de mayor a menor
distribucion_geografica = distribucion_geografica.sort_values(
    'total_empleados', ascending=False
).reset_index(drop=True)

# Renombrar columnas para presentación
distribucion_geografica.columns = ['Región', 'Total Empleados', '% del Total']

print('Distribución geográfica del dataset sintético')
print(f'Total registros: {distribucion_geografica["Total Empleados"].sum():,}')
print()
distribucion_geografica

Distribución geográfica del dataset sintético
Total registros: 50,000

   Región  Total Empleados % del Total
0  México            31081       62.2%
1  Europa            11462       22.9%
2     USA             4487        9.0%
3   Latam             2970        5.9%

In [142]:
df_succession.info()

<class 'pandas.DataFrame'>
RangeIndex: 38200 entries, 1 to 38200
Data columns (total 19 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   position_code           38200 non-null  str
 1   job_title               38200 non-null  str
 2   level                   38200 non-null  str
 3   business_unit           38200 non-null  str
 4   incumbent_id            38200 non-null  str
 5   incumbent_name          38200 non-null  str
 6   incumbent_ou            38200 non-null  str
 7   incumbent_dob           38200 non-null  str
 8   incumbent_age           38200 non-null  int64
 9   nominee_id              38200 non-null  str
 10  nominee_name            38200 non-null  str
 11  nominee_gender          38200 non-null  str
 12  nominee_dob             38200 non-null  str
 13  nominee_position_title  38200 non-null  str
 14  nominee_position_code   38200 non-null  str
 15  nominee_business_unit   38200 non-null  str
 16  readiness               38200 non-null  str
 17  nomination_date         38200 non-null  str
 18  nominator_id            38200 non-null  str
dtypes: int64(1), str(18)
memory usage: 5.5 MB

## Actividad 5 - Corrección de tipos y datos temporales

1. Revisar el tipo de dato de cada columna e identificar las interpretadas de manera incorrecta

In [143]:
#Revisión de cada una de las tablas de datos:
print('── Plantilla Global ──')
print(df_plantilla.dtypes.to_string())

── Plantilla Global ──
full_name                     str
gender                        str
date_of_birth                 str
date_of_entry_alfa            str
date_of_entry_sigma           str
direction                     str
management                    str
area                          str
department                    str
site                          str
country                       str
level                         str
ipe                         int64
segment                       str
is_executive                  str
division                      str
job_function                  str
contract_type                 str
employee_group                str
salary_sap                float64
monthly_salary            float64
currency                      str
exchange_rate             float64
monthly_salary_mxn        float64
monthly_salary_usd        float64
bonuses_original          float64
total_compensation_mxn    float64
comp_ratio                float64

In [144]:
print('── Demographics ──')
print(df_demographics.dtypes.to_string())

── Demographics ──
full_name                  str
gender                     str
date_of_birth              str
employee_type              str
position_type              str
date_of_entry_alfa         str
date_of_entry_sigma        str
headcount                int64
age                      int64
tenure_alfa_years      float64
tenure_sigma_years     float64
age_band                   str
tenure_band                str

In [145]:
print('── Candidate Profile ──')
print(df_candidate.dtypes.to_string())

── Candidate Profile ──
full_name                             str
second_surname                        str
phone                               int64
postal_code                         int64
country                               str
state                                 str
municipality                          str
date_of_birth                         str
nationality                           str
civil_status                          str
native_language                       str
profile_visibility                    str
relocation_available                  str
education_degree_1                    str
education_institution_1               str
education_field_1                     str
education_year_1                    int64
education_degree_2                    str
education_institution_2               str
education_field_2                     str
education_year_2                    int64
prev_company_1                        str
prev_title_1                          str
prev_start_1                          str
prev_end_1                            str
prev_company_2                        str
prev_title_2                          str
prev_start_2                          str
prev_end_2                            str
interest_area_1                       str
interest_area_2                       str
certification_1                       str
certification_year_1                int64
certification_2                       str
certification_year_2                int64
language_1                            str
language_1_level                      str
language_2                            str
language_2_level                      str
course_1                              str
course_year_1                       int64
course_2                              str
course_year_2                       int64
leadership_vision                   int64
leadership_influence                int64
leadership_decision_making          int64
functional_execution                int64
functional_innovation               int64
functional_results_orientation      int64
cultural_collaboration              int64
cultural_integrity                  int64
cultural_customer_focus             int64
communication                       int64
adaptability                        int64
learning_agility                    int64
score_leadership                  float64
score_functional                  float64
score_cultural                    float64
score_overall                     float64

In [146]:
print('── Succession ──')
print(df_succession.dtypes.to_string())

── Succession ──
position_code               str
job_title                   str
level                       str
business_unit               str
incumbent_id                str
incumbent_name              str
incumbent_ou                str
incumbent_dob               str
incumbent_age             int64
nominee_id                  str
nominee_name                str
nominee_gender              str
nominee_dob                 str
nominee_position_title      str
nominee_position_code       str
nominee_business_unit       str
readiness                   str
nomination_date             str
nominator_id                str

-Algunas fechas son marcadas como tipo str, eso puede afectar en los calculos de antiguedad de los empleados, deben modificarsse a 'datetime64' 

-los telefonos deben ser identificadores para evitar operaciones aritmeticas con ellos, deben cambiarse a tipo 'str'

In [147]:
#CAmbiar tipo de phone y postal_code por 'str' para la tabla de candidates 

df_candidate['phone'] = df_candidate['phone'].astype(str)
df_candidate['postal_code'] = df_candidate['postal_code'].astype(str) 

#Comprobar los cambios hechos en el tipo de datos
print('─'*12, 'Candidate Profile', '─'*12)
print(df_candidate.dtypes.to_string())

──────────── Candidate Profile ────────────
full_name                             str
second_surname                        str
phone                                 str
postal_code                           str
country                               str
state                                 str
municipality                          str
date_of_birth                         str
nationality                           str
civil_status                          str
native_language                       str
profile_visibility                    str
relocation_available                  str
education_degree_1                    str
education_institution_1               str
education_field_1                     str
education_year_1                    int64
education_degree_2                    str
education_institution_2               str
education_field_2                     str
education_year_2                    int64
prev_company_1                        str
prev_title_1                          str
prev_start_1                          str
prev_end_1                            str
prev_company_2                        str
prev_title_2                          str
prev_start_2                          str
prev_end_2                            str
interest_area_1                       str
interest_area_2                       str
certification_1                       str
certification_year_1                int64
certification_2                       str
certification_year_2                int64
language_1                            str
language_1_level                      str
language_2                            str
language_2_level                      str
course_1                              str
course_year_1                       int64
course_2                              str
course_year_2                       int64
leadership_vision                   int64
leadership_influence                int64
leadership_decision_making          int64
functional_execution                int64
functional_innovation               int64
functional_results_orientation      int64
cultural_collaboration              int64
cultural_integrity                  int64
cultural_customer_focus             int64
communication                       int64
adaptability                        int64
learning_agility                    int64
score_leadership                  float64
score_functional                  float64
score_cultural                    float64
score_overall                     float64

In [148]:
print(f'   phone       → {df_candidate["phone"].dtype}')
print(f'   postal_code → {df_candidate["postal_code"].dtype}')

   phone       → str
   postal_code → str

3. Verificar el cambio de tipo para las fechas:

In [149]:
# Columnas de fecha identificadas en las 4 tablas
fechas_plantilla   = ['date_of_birth', 'date_of_entry_alfa', 'date_of_entry_sigma']
fechas_demo        = ['date_of_birth', 'date_of_entry_alfa', 'date_of_entry_sigma']
fechas_candidate   = ['date_of_birth', 'prev_start_1', 'prev_end_1',
                      'prev_start_2', 'prev_end_2']
fechas_succession  = ['nomination_date', 'incumbent_dob', 'nominee_dob']

for col in fechas_plantilla:
    df_plantilla[col] = pd.to_datetime(df_plantilla[col], errors='coerce')

for col in fechas_demo:
    df_demographics[col] = pd.to_datetime(df_demographics[col], errors='coerce')

for col in fechas_candidate:
    df_candidate[col] = pd.to_datetime(df_candidate[col], errors='coerce')

for col in fechas_succession:
    df_succession[col] = pd.to_datetime(df_succession[col], errors='coerce')

# Verificar resultado
print('— Fechas convertidas a datetime64:\n')
print('Plantilla Global:')
for col in fechas_plantilla:
    print(f'   {col} → {df_plantilla[col].dtype}')
print('\nDemographics:')
for col in fechas_demo:
    print(f'   {col} → {df_demographics[col].dtype}')
print('\nCandidate Profile:')
for col in fechas_candidate:
    print(f'   {col} → {df_candidate[col].dtype}')
print('\nSuccession:')
for col in fechas_succession:
    print(f'   {col} → {df_succession[col].dtype}')

— Fechas convertidas a datetime64:

Plantilla Global:
   date_of_birth → datetime64[us]
   date_of_entry_alfa → datetime64[us]
   date_of_entry_sigma → datetime64[us]

Demographics:
   date_of_birth → datetime64[us]
   date_of_entry_alfa → datetime64[us]
   date_of_entry_sigma → datetime64[us]

Candidate Profile:
   date_of_birth → datetime64[us]
   prev_start_1 → datetime64[us]
   prev_end_1 → datetime64[us]
   prev_start_2 → datetime64[us]
   prev_end_2 → datetime64[us]

Succession:
   nomination_date → datetime64[us]
   incumbent_dob → datetime64[us]
   nominee_dob → datetime64[us]

4. Derivar componentes temporales útiles para el análisis, como año, mes o día de la semana, cuando los datos lo permitan.

In [150]:
#Realizamos importación de libreria datetime
from datetime import date

hoy = pd.Timestamp.today()

# ── Demographics ───
# Año de ingreso a Sigma (útil para análisis de cohortes)
df_demographics['entry_sigma_year'] = df_demographics['date_of_entry_sigma'].dt.year

# Mes de ingreso (¿hay estacionalidad en contrataciones?)
df_demographics['entry_sigma_month'] = df_demographics['date_of_entry_sigma'].dt.month

# Antigüedad recalculada desde fecha real (más precisa que el campo original)
df_demographics['tenure_sigma_calculated'] = (
    (hoy - df_demographics['date_of_entry_sigma']).dt.days / 365.25
).round(2)

# Edad recalculada desde fecha real
df_demographics['age_calculated'] = (
    (hoy - df_demographics['date_of_birth']).dt.days / 365.25
).astype(int)

# ── Succession ───
# Año y mes de nominación
df_succession['nomination_year']  = df_succession['nomination_date'].dt.year
df_succession['nomination_month'] = df_succession['nomination_date'].dt.month

# Edad del incumbente calculada a.k.a. quién ostenta el la vacante a ser sedida por un candidato potencial
df_succession['incumbent_age_calculated'] = (
    (hoy - df_succession['incumbent_dob']).dt.days / 365.25
).astype(int)

print('Ejemplos de "Componentes temporales derivados":\n')
print('Demographics:')
print(df_demographics[['date_of_entry_sigma','entry_sigma_year',
                        'entry_sigma_month','tenure_sigma_calculated',
                        'age_calculated']].head(3).to_string())
print('\nSuccession:')
print(df_succession[['nomination_date','nomination_year',
                     'nomination_month','incumbent_age_calculated']].head(3).to_string())

Ejemplos de "Componentes temporales derivados":

Demographics:
            date_of_entry_sigma  entry_sigma_year  entry_sigma_month  tenure_sigma_calculated  age_calculated
employee_id
NIP100001            2015-12-28              2015                 12                    10.53              46
NIP100002            2017-02-21              2017                  2                     9.38              34
NIP100003            2021-10-07              2021                 10                     4.75              48

Succession:
              nomination_date  nomination_year  nomination_month  incumbent_age_calculated
nomination_id
1                  2025-07-26             2025                 7                        42
2                  2025-01-19             2025                 1                        34
3                  2024-07-18             2024                 7                        35

5. Crear una columna calculada relevante mediante una operación entre columnas existentes.

In [151]:
# Columna calculada a partir de los años que le faltan al incumbente para llegar a 65 años
# (edad típica de retiro ejecutivo — indica urgencia de sucesión)
df_succession['years_to_retirement'] = (
    65 - df_succession['incumbent_age_calculated']
).clip(lower=0)  # evita valores negativos si ya pasó los 65

# Clasificar urgencia de sucesión
df_succession['succession_urgency'] = pd.cut(
    df_succession['years_to_retirement'],
    bins=[-1, 3, 7, 15, 100],
    labels=['Crítica', 'Alta', 'Media', 'Baja']
)

print('Columna calculada: urgencia de sucesión\n')
print(df_succession[['incumbent_id', 'incumbent_age_calculated',
                      'years_to_retirement',
                      'succession_urgency']].sample(10).to_string())

print('\nDistribución de urgencia:')
print(df_succession['succession_urgency'].value_counts())

Columna calculada: urgencia de sucesión

              incumbent_id  incumbent_age_calculated  years_to_retirement succession_urgency
nomination_id
4122             NIP140944                        47                   18               Baja
27838            NIP129295                        29                   36               Baja
26527            NIP113799                        56                    9              Media
10338            NIP108641                        40                   25               Baja
29234            NIP103091                        34                   31               Baja
17130            NIP128948                        39                   26               Baja
32723            NIP106828                        55                   10              Media
36972            NIP134259                        33                   32               Baja
13250            NIP125251                        29                   36               Baja
27933            NIP120131                        28                   37               Baja

Distribución de urgencia:
succession_urgency
Baja       28290
Media       9306
Alta         604
Crítica        0
Name: count, dtype: int64

## Actividad 6

1. Seleccionar las variables numéricas más vinculadas con el desafío del proyecto.

| Variable | Dataset |
| ---- | ---- |
| monthly_salary_mxn | df_plantilla |
| monthly_salary_usd  | df_plantilla |
| bonuses_original | df_plantilla |
| ipe | df_plantilla |
| comp_ratio | df_plantilla |
| score_overall | df_candidate |
| score_leadership | df_candidate |
| leadership_vision | df_candidate |
| leadership_influence | df_candidate |
| age_calculated | df_demographics |
| tenure_sigma_calculated  | df_demographics |
| incumbent_age_calculated | df_succession |
| years_to_retirement | df_succession |

In [152]:
# Variables de análisis con metadata
VARIABLES = {
    "monthly_salary_mxn": {
        "series"  : df_plantilla["monthly_salary_mxn"],
        "label"   : "Sueldo mensualizado MXN",
        "unit"    : "MXN",
        "source"  : "Plantilla Global",
        "cv_valid": True,
    },
        "monthly_salary_usd": {
        "series"  : df_plantilla["monthly_salary_usd"],
        "label"   : "Sueldo mensualizado USD",
        "unit"    : "USD",
        "source"  : "Plantilla Global",
        "cv_valid": True,
    },
    "bonuses_original": {
        "series"  : df_plantilla["bonuses_original"],
        "label"   : "Bonos y compensaciones",
        "unit"    : "MXN",
        "source"  : "Plantilla Global",
        "cv_valid": True,
    },
    "ipe":{
        "series"  : df_plantilla["ipe"],
        "label"   : "Índice de desempeño empresarial",
        "unit"    : "IPE",
        "source"  : "Plantilla Global",
        "cv_valid": True,
    },
    "comp_ratio":{
        "series"  : df_plantilla["comp_ratio"],
        "label"   : "Comp Ratio",
        "unit"    : "%",
        "source"  : "Plantilla Global",
        "cv_valid": True,
    },
    "score_overall": {
        "series"  : df_candidate["score_overall"],
        "label"   : "Puntaje general del candidato",
        "unit"    : "puntos",
        "source"  : "Candidate Profile",
        "cv_valid": True,
    },
    "score_leadership": {
        "series"  : df_candidate["score_leadership"],
        "label"   : "Puntaje de liderazgo",
        "unit"    : "puntos",
        "source"  : "Candidate Profile",
        "cv_valid": True,
    },
    "leadership_vision": {
        "series"  : df_candidate["leadership_vision"],
        "label"   : "Visión de liderazgo",
        "unit"    : "puntos",
        "source"  : "Candidate Profile",
        "cv_valid": True,
    },
    "leadership_influence": {
        "series"  : df_candidate["leadership_influence"],
        "label"   : "Influencia de liderazgo",
        "unit"    : "puntos",
        "source"  : "Candidate Profile",
        "cv_valid": True,
    },
    "age_calculated": {
        "series"  : df_demographics["age_calculated"],
        "label"   : "Edad del empleado",
        "unit"    : "años",
        "source"  : "Demographics",
        "cv_valid": True,
    },
    "tenure_sigma_calculated": {
        "series"  : df_demographics["tenure_sigma_calculated"],
        "label"   : "Antigüedad del empleado",
        "unit"    : "años",
        "source"  : "Demographics",
        "cv_valid": True,
    },
    "incumbent_age_calculated": {
        "series"  : df_succession["incumbent_age_calculated"],
        "label"   : "Edad del incumbente",
        "unit"    : "años",
        "source"  : "Succession",
        "cv_valid": True,
    },
    "years_to_retirement": {
        "series"  : df_succession["years_to_retirement"],
        "label"   : "Años para retiro del incumbente",
        "unit"    : "años",
        "source"  : "Succession",
        "cv_valid": True,
    },
}

In [153]:
# Se define una función para formatear valores numéricos según su unidad de medida
def fmt(val, unit, decimals=2):
    """
    Formatea un valor numérico según su unidad de medida.
    """
    # Si el valor es None, se retorna "N/A"
    if val is None:
        return "N/A"
    # Si la unidad es "MXN", se formatea como moneda mexicana
    if unit == "MXN":
        return f"${val:,.0f} MXN"
    # Si la unidad es "USD", se formatea como moneda estadounidense
    if unit == "USD":
        return f"${val:,.0f} USD"
    # Si la unidad es "%", se formatea como porcentaje
    if unit == "%":
        return f"{val:.{decimals}f}%"
    # Por defecto, se formatea con el número de decimales especificado
    return f"{val:.{decimals}f} {unit}".strip()

In [154]:
# Validación de datos cargados
print(f"   Variables a analizar: {len(VARIABLES)}\n")

   Variables a analizar: 13

In [155]:
def statistical_analysis(series: pd.Series, name: str, meta: dict) -> dict:
    """
    Calcula medidas de dispersión para una serie de datos númericos

    Retorna diccionario con:
    a) Medidas de tendencia central: media, mediana, moda
    b) Medidas de dispersión: std, varianza, rango, IQR, CV
    c) Cuartiles: Q1, Q2, Q3
    d) Coeficiente de variación (CV) - solo si la media es mayor de cero y sin valores negativos
    e) Cercas IQR: lower_fence, upper_fence
    f) Valores atípicos: outliers
    """
    # Eliminamos valores nulos
    s = series.dropna().astype(float)

    # Se obtiene el tamaño de la muestra
    n = len(s)

    """ a) Medidas de tendencia central: media, mediana, moda """
    # Media
    mean = s.mean()

    # Mediana
    median = s.median()
    
    # Moda
    # Se obtiene la moda, si existe; de lo contrario, se asigna NaN
    mode = s.mode().iloc[0] if not s.mode().empty else np.nan

    # Medida más representativa y simetría de la distribución
    relative_difference = abs(mean - median) / abs(mean) if mean != 0 else 0

    # Se evalua la diferencia relativa
    if relative_difference <= 0.05:
        representative_measure = "Media. La media y mediana son muy similares"
        simetric_inference = "Se infiere una distribución aproximadamente simetrica"
    elif mean > median > mode:
        representative_measure = "Mediana. Se observa un patrón media > mediana > moda"
        simetric_inference = "Se infiere un posible sesgo positivo"
    elif mean < median < mode:
        representative_measure = "Mediana. Se observa un patrón media < mediana < moda"
        simetric_inference = "Se infiere un posible sesgo negativo"
    else:
        representative_measure = "No hay una medida claramente representativa"
        simetric_inference = "Se requiere revisión manual"

    # Variables donde la media y la mediana difieren de manera notable
    # y explicar qué indica esa diferencia.

    # Diferencia entre media y mediana y porcentaje
    difference = abs(mean - median)
    difference_pct = difference / abs(mean) * 100 if mean != 0 else 0

    # Se evalua el porcentaje de la diferencia
    if difference_pct < 5:
        difference_explanation = "No hay diferencia notable entre la media y mediana, indicando una distribución relativamente simétrica."
    elif mean > median:
        difference_explanation = "La media es mayor que la mediana, lo que sugiere una asimetría positiva (cola hacia la derecha)."
    else:
        difference_explanation = "La media es menor que la mediana, lo que indica una posible asimetría negativa (cola hacia la izquierda)."

    """ ACT 7 b) Medidas de dispersión: std, varianza, rango, IQR y CV """
    
    # Desviación estándar
    std = s.std(ddof=1)

    #Varianza
    variance = s.var(ddof=1)

    # Rango
    rng = s.max() - s.min()

    # Coeficiente de variación
    # Se interpreta cuánto varía la desviación estándar respecto de su valor central (media)
    cv = std / mean * 100 if (meta["cv_valid"] and mean > 0) else None

    # Clasificación del coeficiente de variación
    if cv is None:
        cv_classification = "N/A"
        cv_explanation = "No se puede calcular el CV debido a que la media es cero o hay valores negativos."
    if cv < 20:
        cv_classification = "Muy baja (<20%)"
        cv_explanation = "La variación es muy baja, lo que indica una distribución relativamente homogénea."
    elif cv < 35:
        cv_classification = "Baja (20–35%)"
        cv_explanation = "La variación es baja, lo que indica una distribución relativamente homogénea."
    elif cv < 50:
        cv_classification = "Media (35–50%)"
        cv_explanation = "La variación es media, lo que indica una distribución con una variabilidad moderada."
    else:
        cv_classification = "Alta (>50%)"
        cv_explanation = "La variación es alta, lo que indica una distribución con una gran dispersión de valores."

    """ c) Cuartiles """
    # Q1 (Cuarto 1)
    q1 = s.quantile(0.25)

    # Q2 (Cuarto 2) igual a la mediana
    q2 = s.quantile(0.50)

    # Q3 (Cuarto 3)
    q3 = s.quantile(0.75)

    # Rango intercuartílico
    iqr = q3 - q1 


    """e) Cercas IQR """
    # Cerca inferior
    lower_fence = q1 - 1.5 * iqr

    # Cerca superior
    upper_fence = q3 + 1.5 * iqr

    #Cerca inferior extrema
    lower_fence_extreme = q1 - 3.0 * iqr
    
    # Cerca superior extrema
    upper_fence_extreme = q3 + 3.0 * iqr

    """f) Valores atípicos """
    # Valores atípicos por debajo de la cerca inferior
    outliers_low = s[s < lower_fence]

    # Valores atípicos por encima de la cerca superior
    outliers_high = s[s > upper_fence]

    # Valores atípicos por encima de la cerca superior extrema
    extreme_low = s[s < lower_fence_extreme]

    # Valores atípicos por debajo de la cerca inferior extrema
    extreme_high = s[s > upper_fence_extreme]

    # Valores atípicos estándar (outliers)
    out_std = s[(s < lower_fence) | (s > upper_fence)]

    # Valores atípicos extremos (outliers extremos)
    out_ext = s[(s < lower_fence_extreme) | (s > upper_fence_extreme)]
    
    # Se obtiene el tamaño de los valores atípicos
    n_out   = len(out_std)

    # Se obtiene el tamaño de los valores atípicos extremos
    n_ext   = len(out_ext)

    # Porcentaje de valores atípicos
    pct_out = (n_out / n * 100) if n > 0 else 0

    # Cálculo de la asimetría (skewness)
    skew = s.skew()

    # Cálculo de la curtosis (kurtosis)
    kurt = s.kurtosis()

    # Percentil 10
    p10 = s.quantile(0.10)

    # Percentil 90
    p90 = s.quantile(0.90)

    # Se retorna un diccionario con los resultados del análisis
    return{
        "name"  : name,
        "label" : meta["label"],
        "unit"  : meta["unit"],
        "source": meta["source"],
        "n"     : n,
        "mean"  : mean,
        "median": median,
        "mode"  : mode,
        "representative_measure": representative_measure,
        "simetric_inference": simetric_inference,
        "difference_pct": difference_pct,
        "difference_explanation": difference_explanation,
        "std"   : std,
        "variance": variance,
        "range" : rng,
        "q1"    : q1,
        "q2"    : q2,
        "q3"    : q3,
        "iqr"   : iqr,
        "p10"   : p10,
        "p90"   : p90,
        "cv"    : cv,
        "cv_classification": cv_classification,
        "cv_explanation": cv_explanation,
        "lower_fence": lower_fence,
        "upper_fence": upper_fence,
        "lower_fence_extreme": lower_fence_extreme,
        "upper_fence_extreme": upper_fence_extreme,
        "outliers_low": outliers_low,
        "outliers_high": outliers_high,
        "extreme_low": extreme_low,
        "extreme_high": extreme_high,
        "outliers": out_std,
        "n_out" : n_out,
        "n_ext" : n_ext,
        "pct_out": pct_out,
        "skew"  : skew,
        "kurt"  : kurt,
    }

In [156]:
# Se realiza el bucle para analizar cada variable definida en el diccionario VARIABLES 
# y almacenar los resultados en un nuevo diccionario results
results = {}

for var_name, meta in VARIABLES.items():
    results[var_name] = statistical_analysis(meta["series"], var_name, meta)

2. Calcular la media, la mediana y la moda de cada variable.

In [157]:
# Se calcula media, mediana y moda de cada variable y se imprime en una tabla
print(f"\n  {'Variable':<25} {'Unidad':>18} {'Tamaño de muestra':>18} {'Media':>18} {'Mediana':>18} {'Moda':>18}")
# Se imprime una línea divisoria para la tabla
print(f"  {'─'*25} {'─'*18} {'─'*18} {'─'*18} {'─'*18} {'─'*18}")
# Se imprime cada variable
for name, r in results.items():
    u = r["unit"]
    print(f"  {name:<25} {r['unit']:<18} {r['n']:>18} {fmt(r['mean'],u):>18} {fmt(r['median'],u):>18} {fmt(r['mode'],u):>18}")

  Variable                              Unidad  Tamaño de muestra              Media            Mediana               Moda
  ───────────────────────── ────────────────── ────────────────── ────────────────── ────────────────── ──────────────────
  monthly_salary_mxn        MXN                             50000       $760,168 MXN       $621,433 MXN         $2,279 MXN
  monthly_salary_usd        USD                             50000        $43,438 USD        $35,510 USD            $82 USD
  bonuses_original          MXN                             50000         $4,423 MXN         $3,250 MXN           $188 MXN
  ipe                       IPE                             50000          12.96 IPE          12.00 IPE           8.00 IPE
  comp_ratio                %                               50000             99.59%             99.70%             70.20%
  score_overall             puntos                          50000       64.44 puntos       64.40 puntos       63.20 puntos
  score_leadership          puntos                          50000       64.45 puntos       64.70 puntos       63.30 puntos
  leadership_vision         puntos                          50000       64.42 puntos       64.00 puntos       63.00 puntos
  leadership_influence      puntos                          50000       64.48 puntos       65.00 puntos       66.00 puntos
  age_calculated            años                            50000         41.50 años         41.00 años         35.00 años
  tenure_sigma_calculated   años                            50000          8.68 años          7.19 años          2.74 años
  incumbent_age_calculated  años                            38200         41.58 años         42.00 años         37.00 años
  years_to_retirement       años                            38200         23.42 años         23.00 años         28.00 años

3. Determinar qué medida representa mejor a cada variable según su comportamiento.

In [158]:
# Analizar qué medida representa mejor a cada variable según su comportamiento
print(f"\n  {'Variable':<25} {'Medida más representativa':>55}")

# Se imprime una línea divisoria para la tabla
print(f"  {'─'*25} {'─'*55}")

# Se imprime cada variable
for name, r in results.items():
    print(f"  {name:<25} {r['representative_measure']:<55}")

  Variable                                                Medida más representativa
  ───────────────────────── ───────────────────────────────────────────────────────
  monthly_salary_mxn        Mediana. Se observa un patrón media > mediana > moda
  monthly_salary_usd        Mediana. Se observa un patrón media > mediana > moda
  bonuses_original          Mediana. Se observa un patrón media > mediana > moda
  ipe                       Mediana. Se observa un patrón media > mediana > moda
  comp_ratio                Media. La media y mediana son muy similares
  score_overall             Media. La media y mediana son muy similares
  score_leadership          Media. La media y mediana son muy similares
  leadership_vision         Media. La media y mediana son muy similares
  leadership_influence      Media. La media y mediana son muy similares
  age_calculated            Media. La media y mediana son muy similares
  tenure_sigma_calculated   Mediana. Se observa un patrón media > mediana > moda
  incumbent_age_calculated  Media. La media y mediana son muy similares
  years_to_retirement       Media. La media y mediana son muy similares

4. Inferir, a partir de los estadísticos disponibles, si existen indicios de simetría, sesgo o concentración de valores.

In [159]:
# Analizar si existen indicios de simetría, sesgo o concentración de valores
print(f"\n  {'Variable':<25} {'Medida más representativa':>55} {'Indicios de simetría':>55}")

# Se imprime una línea divisoria para la tabla
print(f"  {'─'*25} {'─'*55} {'─'*55}")

# Se imprime cada variable
for name, r in results.items():
    print(f"  {name:<25} {r['representative_measure']:<55} {r['simetric_inference']:<55}")

  Variable                                                Medida más representativa                                    Indicios de simetría
  ───────────────────────── ─────────────────────────────────────────────────────── ───────────────────────────────────────────────────────
  monthly_salary_mxn        Mediana. Se observa un patrón media > mediana > moda    Se infiere un posible sesgo positivo
  monthly_salary_usd        Mediana. Se observa un patrón media > mediana > moda    Se infiere un posible sesgo positivo
  bonuses_original          Mediana. Se observa un patrón media > mediana > moda    Se infiere un posible sesgo positivo
  ipe                       Mediana. Se observa un patrón media > mediana > moda    Se infiere un posible sesgo positivo
  comp_ratio                Media. La media y mediana son muy similares             Se infiere una distribución aproximadamente simetrica
  score_overall             Media. La media y mediana son muy similares             Se infiere una distribución aproximadamente simetrica
  score_leadership          Media. La media y mediana son muy similares             Se infiere una distribución aproximadamente simetrica
  leadership_vision         Media. La media y mediana son muy similares             Se infiere una distribución aproximadamente simetrica
  leadership_influence      Media. La media y mediana son muy similares             Se infiere una distribución aproximadamente simetrica
  age_calculated            Media. La media y mediana son muy similares             Se infiere una distribución aproximadamente simetrica
  tenure_sigma_calculated   Mediana. Se observa un patrón media > mediana > moda    Se infiere un posible sesgo positivo
  incumbent_age_calculated  Media. La media y mediana son muy similares             Se infiere una distribución aproximadamente simetrica
  years_to_retirement       Media. La media y mediana son muy similares             Se infiere una distribución aproximadamente simetrica

5. Identificar las variables donde la media y la mediana difieren de manera notable, y explicar qué indica esa diferencia.

In [160]:
# Se identifica la diferencia de media y mediana y su conclusión
print(f"\n  {'Variable':<25} {'Diferencia % entre media y mediana':>40} {'Conclusión':>100}")

# Se imprime una línea divisoria para la tabla
print(f"  {'─'*25} {'─'*40} {'─'*100}")

# Se imprime cada variable
for name, r in results.items():
    print(f"  {name:<25} {r['difference_pct']:.2f}%{'':>40} {r['difference_explanation']:<100}")

  Variable                        Diferencia % entre media y mediana                                                                                           Conclusión
  ───────────────────────── ──────────────────────────────────────── ────────────────────────────────────────────────────────────────────────────────────────────────────
  monthly_salary_mxn        18.25%                                         La media es mayor que la mediana, lo que sugiere una asimetría positiva (cola hacia la derecha).
  monthly_salary_usd        18.25%                                         La media es mayor que la mediana, lo que sugiere una asimetría positiva (cola hacia la derecha).
  bonuses_original          26.52%                                         La media es mayor que la mediana, lo que sugiere una asimetría positiva (cola hacia la derecha).
  ipe                       7.38%                                         La media es mayor que la mediana, lo que sugiere una asimetría positiva (cola hacia la derecha).
  comp_ratio                0.11%                                         No hay diferencia notable entre la media y mediana, indicando una distribución relativamente simétrica.
  score_overall             0.06%                                         No hay diferencia notable entre la media y mediana, indicando una distribución relativamente simétrica.
  score_leadership          0.39%                                         No hay diferencia notable entre la media y mediana, indicando una distribución relativamente simétrica.
  leadership_vision         0.65%                                         No hay diferencia notable entre la media y mediana, indicando una distribución relativamente simétrica.
  leadership_influence      0.81%                                         No hay diferencia notable entre la media y mediana, indicando una distribución relativamente simétrica.
  age_calculated            1.20%                                         No hay diferencia notable entre la media y mediana, indicando una distribución relativamente simétrica.
  tenure_sigma_calculated   17.13%                                         La media es mayor que la mediana, lo que sugiere una asimetría positiva (cola hacia la derecha).
  incumbent_age_calculated  1.02%                                         No hay diferencia notable entre la media y mediana, indicando una distribución relativamente simétrica.
  years_to_retirement       1.81%                                         No hay diferencia notable entre la media y mediana, indicando una distribución relativamente simétrica.

6. Sintetizar los principales resultados del perfil estadístico en lenguaje de negocio.

In [161]:
# Resumen de negocio para cada variable analizada
resumen_negocio = {
    "monthly_salary_mxn": (
        "La media salarial ($760k MXN) supera en 22% a la mediana ($621k). \n"
        "Esto refleja que un grupo pequeño de ejecutivos N1 eleva la media. "
        "Para análisis de equidad salarial, usar la mediana y segmentar por nivel."
    ),
    "monthly_salary_usd": (
        "Mismo patrón que el salario MXN (CV=89.9%). Ambas columnas representan"
        "la misma compensación en distinta moneda; la dispersión es estructural por nivel, "
        "no un error de datos."
    ),
    "bonuses_original": (
        "El bono mediano es $3,250 MXN, pero la media es $4,423 (CV=94.7%). "
        "Alta variabilidad por la mezcla de perfiles con y sin comisiones variables."
    ),
    "ipe": (
        "IPE tiene CV=27% con media de 13 puntos. Refleja la estructura de niveles "
        "(N1–N5) de forma homogénea. Útil como variable de control en modelos."
    ),
    "comp_ratio": (
        "Mediana=99.7%, media=99.6% — distribución casi simétrica. "
        "La mayoría de empleados está posicionada en el punto medio de su banda salarial."
    ),
    "score_overall": (
        "Score_General tiene IQR de solo 5.7 puntos (escala 47–82). \n"
        "El promedio de promedios comprime la variabilidad real. "
        "No discrimina bien entre candidatos — usar competencias individuales para ranking."
    ),
    "score_leadership": (
        "Mayor dispersión que score_overall (IQR=11.6 pts). "
        "Diferencia real entre perfiles de liderazgo fuerte y perfiles operativos."
    ),
    "leadership_vision": (
        "CV=23.2% con distribución simétrica. Discrimina moderadamente. "
        "Los 163 outliers bajos (1–22 pts) merecen verificación de evaluaciones incompletas."
    ),
    "leadership_influence": (
        "Patrón similar a leadership_vision. 127 outliers bajos (4–22 pts)."
    ),
    "age_calculated": (
        "Distribución uniforme entre 24 y 57 años (IQR=17 años). "
        "Plantilla equilibrada generacionalmente con CV=23.2%."
    ),
    "tenure_sigma_calculated": (
        "CV=64.3% — la variable más heterogénea de demographics. "
        "Coexisten empleados de meses con empleados fundadores (>22 años). \n"
        "Cola derecha marcada; usar mediana (7.2 años) sobre la media (8.2 años)."
    ),
    "incumbent_age_calculated": (
        "Edad media de titulares: 41.6 años. Rango 24–57 con distribución uniforme. "
        "Ningún titular está cerca de los 65 años (retiro) con la fecha de corte 2026-01-01."
    ),
    "years_to_retirement": (
        "Mediana de 23.4 años para el retiro. Zona 'Alta' (6–10 años): 604 titulares "
        "que representan el principal foco de planificación de sucesión a mediano plazo."
    ),
}

for name, texto in resumen_negocio.items():
    r = results[name]
    print(f"\n {r['label']} [{r['source']}]")
    print(f"  {texto}")

 Sueldo mensualizado MXN [Plantilla Global]
  La media salarial ($760k MXN) supera en 22% a la mediana ($621k).
Esto refleja que un grupo pequeño de ejecutivos N1 eleva la media. Para análisis de equidad salarial, usar la mediana y segmentar por nivel.

 Sueldo mensualizado USD [Plantilla Global]
  Mismo patrón que el salario MXN (CV=89.9%). Ambas columnas representanla misma compensación en distinta moneda; la dispersión es estructural por nivel, no un error de datos.

 Bonos y compensaciones [Plantilla Global]
  El bono mediano es $3,250 MXN, pero la media es $4,423 (CV=94.7%). Alta variabilidad por la mezcla de perfiles con y sin comisiones variables.

 Índice de desempeño empresarial [Plantilla Global]
  IPE tiene CV=27% con media de 13 puntos. Refleja la estructura de niveles (N1–N5) de forma homogénea. Útil como variable de control en modelos.

 Comp Ratio [Plantilla Global]
  Mediana=99.7%, media=99.6% — distribución casi simétrica. La mayoría de empleados está posicionada en el punto medio de su banda salarial.

 Puntaje general del candidato [Candidate Profile]
  Score_General tiene IQR de solo 5.7 puntos (escala 47–82).
El promedio de promedios comprime la variabilidad real. No discrimina bien entre candidatos — usar competencias individuales para ranking.

 Puntaje de liderazgo [Candidate Profile]
  Mayor dispersión que score_overall (IQR=11.6 pts). Diferencia real entre perfiles de liderazgo fuerte y perfiles operativos.

 Visión de liderazgo [Candidate Profile]
  CV=23.2% con distribución simétrica. Discrimina moderadamente. Los 163 outliers bajos (1–22 pts) merecen verificación de evaluaciones incompletas.

 Influencia de liderazgo [Candidate Profile]
  Patrón similar a leadership_vision. 127 outliers bajos (4–22 pts).

 Edad del empleado [Demographics]
  Distribución uniforme entre 24 y 57 años (IQR=17 años). Plantilla equilibrada generacionalmente con CV=23.2%.

 Antigüedad del empleado [Demographics]
  CV=64.3% — la variable más heterogénea de demographics. Coexisten empleados de meses con empleados fundadores (>22 años).
Cola derecha marcada; usar mediana (7.2 años) sobre la media (8.2 años).

 Edad del incumbente [Succession]
  Edad media de titulares: 41.6 años. Rango 24–57 con distribución uniforme. Ningún titular está cerca de los 65 años (retiro) con la fecha de corte 2026-01-01.

 Años para retiro del incumbente [Succession]
  Mediana de 23.4 años para el retiro. Zona 'Alta' (6–10 años): 604 titulares que representan el principal foco de planificación de sucesión a mediano plazo.

## Actividad 7
El perfil estadístico se completa al medir la dispersión y detectar valores atípicos sobre esas mismas variables. Estas medidas permiten evaluar cuánto varían los datos y qué casos requieren revisión antes de la limpieza.

1. Calcular las medidas de dispersión de cada variable e interpretar cuánto varían los datos respecto de su valor central.

In [162]:
# Se analizan las medidas de dispersión y su interpretación
print(f"\n  {'Variable':<25} {'Desviación estándar':>18} {'Varianza':>25} {'Rango':>18} {'Variación respecto a valor central':>35}")
# Se imprime una línea divisoria para la tabla
print(f"  {'─'*25} {'─'*18} {'─'*25} {'─'*18} {'─'*35}")
# Se imprime cada variable con su desviación estandar, varianza, rango y variación respecto a valor central
for name, r in results.items():
    u = r["unit"]
    print(f"  {name:<25} {fmt(r['std'],u):>18} {fmt(r['variance'],u):>25} {fmt(r['range'],u):>18} {r['cv_classification']:<35}")

  Variable                  Desviación estándar                  Varianza              Rango  Variación respecto a valor central
  ───────────────────────── ────────────────── ───────────────────────── ────────────────── ───────────────────────────────────
  monthly_salary_mxn              $683,234 MXN      $466,808,603,181 MXN     $2,098,771 MXN Alta (>50%)
  monthly_salary_usd               $39,042 USD        $1,524,272,990 USD       $119,930 USD Alta (>50%)
  bonuses_original                  $4,188 MXN           $17,536,076 MXN        $17,896 MXN Alta (>50%)
  ipe                                 3.52 IPE                 12.37 IPE          10.00 IPE Baja (20–35%)
  comp_ratio                            15.85%                   251.24%             59.80% Muy baja (<20%)
  score_overall                    4.28 puntos              18.33 puntos       35.10 puntos Muy baja (<20%)
  score_leadership                 8.60 puntos              73.91 puntos       70.40 puntos Muy baja (<20%)
  leadership_vision               14.94 puntos             223.34 puntos       99.00 puntos Baja (20–35%)
  leadership_influence            14.89 puntos             221.83 puntos       96.00 puntos Baja (20–35%)
  age_calculated                     9.53 años                90.91 años         33.00 años Baja (20–35%)
  tenure_sigma_calculated            5.25 años                27.56 años         23.70 años Alta (>50%)
  incumbent_age_calculated           9.51 años                90.42 años         33.00 años Baja (20–35%)
  years_to_retirement                9.51 años                90.42 años         33.00 años Media (35–50%)

2. Comparar la dispersión relativa entre variables mediante el coeficiente de variación, cuando su uso sea pertinente.

In [163]:
# Se compara dispersión de cada variable con su coeficiente de variación (CV) y se interpreta
print(f"\n  {'Variable':<25} {'Coeficiente de variación':>18} {'Interpretación':>80}")
# Se imprime una línea divisoria para la tabla
print(f"  {'─'*25} {'─'*18} {'─'*80}")
# Se imprime cada variable con su coeficiente de variación
for name, r in results.items():
    u = r["unit"]
    print(f"  {name:<25} {r['cv']:.2f}%{'':>18} {r['cv_explanation']:<80}")

  Variable                  Coeficiente de variación                                                                   Interpretación
  ───────────────────────── ────────────────── ────────────────────────────────────────────────────────────────────────────────
  monthly_salary_mxn        89.88%                   La variación es alta, lo que indica una distribución con una gran dispersión de valores.
  monthly_salary_usd        89.88%                   La variación es alta, lo que indica una distribución con una gran dispersión de valores.
  bonuses_original          94.68%                   La variación es alta, lo que indica una distribución con una gran dispersión de valores.
  ipe                       27.14%                   La variación es baja, lo que indica una distribución relativamente homogénea.
  comp_ratio                15.92%                   La variación es muy baja, lo que indica una distribución relativamente homogénea.
  score_overall             6.64%                   La variación es muy baja, lo que indica una distribución relativamente homogénea.
  score_leadership          13.34%                   La variación es muy baja, lo que indica una distribución relativamente homogénea.
  leadership_vision         23.20%                   La variación es baja, lo que indica una distribución relativamente homogénea.
  leadership_influence      23.10%                   La variación es baja, lo que indica una distribución relativamente homogénea.
  age_calculated            22.98%                   La variación es baja, lo que indica una distribución relativamente homogénea.
  tenure_sigma_calculated   60.51%                   La variación es alta, lo que indica una distribución con una gran dispersión de valores.
  incumbent_age_calculated  22.87%                   La variación es baja, lo que indica una distribución relativamente homogénea.
  years_to_retirement       40.59%                   La variación es media, lo que indica una distribución con una variabilidad moderada.

3. Calcular los cuartiles y el rango intercuartílico de las variables seleccionadas.

In [164]:
# Se imprime la tabla de cuartiles y rango intercuartílico (IQR) para cada variable
print(f"\n  {'Variable':<25} {'Q1':>18} {'Q2(Med)':>18} {'Q3':>18} {'IQR':>18}")
# Se imprime una línea divisoria para la tabla
print(f"  {'─'*25} {'─'*18} {'─'*18} {'─'*18} {'─'*18}")
# Se imprime cada variable con sus cuartiles y rango intercuartílico
for name, r in results.items():
    u = r["unit"]
    print(f"  {name:<25} {fmt(r['q1'],u):>18} {fmt(r['q2'],u):>18} {fmt(r['q3'],u):>18} {fmt(r['iqr'],u):>18}")

  Variable                                  Q1            Q2(Med)                 Q3                IQR
  ───────────────────────── ────────────────── ────────────────── ────────────────── ──────────────────
  monthly_salary_mxn              $101,926 MXN       $621,433 MXN     $1,362,060 MXN     $1,260,133 MXN
  monthly_salary_usd                $5,824 USD        $35,510 USD        $77,832 USD        $72,008 USD
  bonuses_original                    $665 MXN         $3,250 MXN         $7,186 MXN         $6,521 MXN
  ipe                                10.00 IPE          12.00 IPE          16.00 IPE           6.00 IPE
  comp_ratio                            88.00%             99.70%            111.00%             23.00%
  score_overall                   61.60 puntos       64.40 puntos       67.30 puntos        5.70 puntos
  score_leadership                58.70 puntos       64.70 puntos       70.30 puntos       11.60 puntos
  leadership_vision               54.00 puntos       64.00 puntos       75.00 puntos       21.00 puntos
  leadership_influence            54.00 puntos       65.00 puntos       75.00 puntos       21.00 puntos
  age_calculated                    33.00 años         41.00 años         50.00 años         17.00 años
  tenure_sigma_calculated            4.34 años          7.19 años         11.86 años          7.52 años
  incumbent_age_calculated          33.00 años         42.00 años         50.00 años         17.00 años
  years_to_retirement               15.00 años         23.00 años         32.00 años         17.00 años

4. Detectar valores atípicos mediante el método del IQR y registrar su cantidad por variable.

In [165]:
# Despliegue de los resultados de valores atípicos para cada variable
print(f"\n  {'Variable':<25} {'Cerca inf':>18} {'Cerca sup':>18} {'N atíp.':>18} {'%':>18}")
# Se imprime una línea divisoria para la tabla
print(f"  {'─'*25} {'─'*18} {'─'*18} {'─'*18} {'─'*18}")
# Bucle para imprimir cada variable con sus cercas IQR, número de valores atípicos y porcentaje
for name, r in results.items():
    u = r["unit"]
    flag = "!!!" if r["n_out"] > 0 else ""
    print(f"  {name:<25} {fmt(r['lower_fence'],u):>18} {fmt(r['upper_fence'],u):>18} "
          f"{r['n_out']:>18}{flag:2} {r['pct_out']:>18.1f}%")

# Se imprime el total de valores atípicos detectados en todas las variables
print(f"\n  Total de atípicos detectados: "
      f"{sum(r['n_out'] for r in results.values())}")

  Variable                           Cerca inf          Cerca sup            N atíp.                  %
  ───────────────────────── ────────────────── ────────────────── ────────────────── ──────────────────
  monthly_salary_mxn           $-1,788,274 MXN     $3,252,259 MXN                  0                  0.0%
  monthly_salary_usd             $-102,187 USD       $185,843 USD                  0                  0.0%
  bonuses_original                 $-9,117 MXN        $16,968 MXN                 85!!!                0.2%
  ipe                                 1.00 IPE          25.00 IPE                  0                  0.0%
  comp_ratio                            53.50%            145.50%                  0                  0.0%
  score_overall                   53.05 puntos       75.85 puntos                357!!!                0.7%
  score_leadership                41.30 puntos       87.70 puntos                347!!!                0.7%
  leadership_vision               22.50 puntos      106.50 puntos                163!!!                0.3%
  leadership_influence            22.50 puntos      106.50 puntos                127!!!                0.3%
  age_calculated                     7.50 años         75.50 años                  0                  0.0%
  tenure_sigma_calculated           -6.94 años         23.14 años                495!!!                1.0%
  incumbent_age_calculated           7.50 años         75.50 años                  0                  0.0%
  years_to_retirement              -10.50 años         57.50 años                  0                  0.0%

  Total de atípicos detectados: 1574

5. Clasificar los valores detectados como posibles errores de carga o casos extremos legítimos según el contexto del negocio.

In [166]:
# Clasificación de la cantidad de valores atípicos por variable
# ─ ERROR DE CARGA:   valor fuera del dominio lógico, inconsistente con otras columnas
#                     o físicamente imposible (ej. antigüedad negativa, edad < 18)
# ─ CASO LEGÍTIMO:    valor extremo estadístico pero coherente con el negocio
# ─ REQUIERE REVISIÓN: valor en escala válida pero sospechosamente bajo/alto

# Se crea un diccionario para clasificar los valores atípicos
CLASIFICACION_ATIPICOS = {
    "bonuses_original": {
        "n_out": results["bonuses_original"]["n_out"],
        "zona": f"Superiores al LS (${results['bonuses_original']['upper_fence']:,.0f} MXN)",
        "rango_out": f"${results['bonuses_original']['outliers'].min():,.0f} – ${results['bonuses_original']['outliers'].max():,.0f}",
        "tipo": "CASO LEGÍTIMO",
        "razon": (
            "Bonos entre $16,974 y $17,962 MXN corresponden a posiciones N1/N2 "
            "con comisiones variables de alto desempeño. Ninguno es extremo (n_ext=0). "
            "Acción: verificar que coincidan con la categoría de puesto (fuerza de ventas)."
        ),
    },
    "score_overall": {
        "n_out": results["score_overall"]["n_out"],
        "zona": f"Bajos (<{results['score_overall']['lower_fence']:.1f}) y altos (>{results['score_overall']['upper_fence']:.1f})",
        "rango_out": "47.0–53.0 (bajos) y 75.9–82.1 (altos)",
        "tipo": "CASO LEGÍTIMO",
        "razon": (
            "Todos dentro de la escala válida [47–82]. Los scores bajos representan "
            "perfiles junior en evaluación temprana; los altos son candidatos de alto "
            "potencial. El IQR pequeño (5.7 pts) hace que incluso valores moderados "
            "aparezcan como atípicos estadísticamente."
        ),
    },
    "score_leadership": {
        "n_out": results["score_leadership"]["n_out"],
        "zona": f"Bajos (<{results['score_leadership']['lower_fence']:.1f}) y altos (>{results['score_leadership']['upper_fence']:.1f})",
        "rango_out": "27.3–41.3 (bajos) y 87.7–97.7 (altos)",
        "tipo": "CASO LEGÍTIMO",
        "razon": (
            "Los 201 perfiles bajos (<41.3) son candidatos con orientación operativa "
            "sin perfil de liderazgo — válidos en la plantilla. Los 146 con score alto "
            "(>87.7) son candidatos ejecutivos potenciales. Ninguno está fuera de escala."
        ),
    },
    "leadership_vision": {
        "n_out": results["leadership_vision"]["n_out"],
        "zona": f"Solo bajos (<{results['leadership_vision']['lower_fence']:.1f} pts)",
        "rango_out": "1–22 puntos",
        "tipo": "REQUIERE REVISIÓN",
        "razon": (
            "163 registros con visión de liderazgo entre 1 y 22 puntos (escala 0–100). "
            "Aunque están dentro del rango válido, valores tan bajos podrían indicar "
            "evaluaciones no completadas o perfiles ingresados en blanco. "
            "Acción: cruzar con 'profile_visibility' y verificar si tienen score_overall > 0."
        ),
    },
    "leadership_influence": {
        "n_out": results["leadership_influence"]["n_out"],
        "zona": f"Solo bajos (<{results['leadership_influence']['lower_fence']:.1f} pts)",
        "rango_out": "4–22 puntos",
        "tipo": "REQUIERE REVISIÓN",
        "razon": (
            "Mismo patrón que leadership_vision. 127 registros con influencia de "
            "liderazgo extremadamente baja. Acción: verificar si coinciden con los mismos "
            "163 de leadership_vision para determinar si son perfiles incompletos."
        ),
    },
    "tenure_sigma_calculated": {
        "n_out": results["tenure_sigma_calculated"]["n_out"],
        "zona": f"Superiores al LS ({results['tenure_sigma_calculated']['upper_fence']:.1f} años)",
        "rango_out": "22.6–25.7 años",
        "tipo": "CASO LEGÍTIMO",
        "razon": (
            "494 empleados con más de 22 años en Sigma — representan el grupo fundador "
            "de la empresa (Sigma lleva ~25 años en operación). Son los empleados con "
            "mayor conocimiento institucional y, paradójicamente, mayor riesgo de retiro."
        ),
    },
}

# Se imprime un resumen de los valores atípicos detectados y su clasificación
print(f"\n  {'Variable':<25} {'N atípicos':>18} {'Zona de atípicos':>40} {'Rango de atípicos':>40} {'Tipo de atípico':>20} {'Razón':>100}")
# Se imprime una línea divisoria para la tabla  
print(f"  {'─'*25} {'─'*18} {'─'*40} {'─'*40} {'─'*20} {'─'*100}")
# Se imprime cada variable con su número de valores atípicos, zona, rango, tipo y razón
for name, r in CLASIFICACION_ATIPICOS.items():
    print(f"  {name:<25} {r['n_out']:>18} {r['zona']:<40} {r['rango_out']:<40} {r['tipo']:<20} {r['razon']:<100}")

  Variable                          N atípicos                         Zona de atípicos                        Rango de atípicos      Tipo de atípico                                                                                                Razón
  ───────────────────────── ────────────────── ──────────────────────────────────────── ──────────────────────────────────────── ──────────────────── ────────────────────────────────────────────────────────────────────────────────────────────────────
  bonuses_original                          85 Superiores al LS ($16,968 MXN)           $16,974 – $17,962                        CASO LEGÍTIMO        Bonos entre $16,974 y $17,962 MXN corresponden a posiciones N1/N2 con comisiones variables de alto desempeño. Ninguno es extremo (n_ext=0). Acción: verificar que coincidan con la categoría de puesto (fuerza de ventas).
  score_overall                            357 Bajos (<53.1) y altos (>75.8)            47.0–53.0 (bajos) y 75.9–82.1 (altos)    CASO LEGÍTIMO        Todos dentro de la escala válida [47–82]. Los scores bajos representan perfiles junior en evaluación temprana; los altos son candidatos de alto potencial. El IQR pequeño (5.7 pts) hace que incluso valores moderados aparezcan como atípicos estadísticamente.
  score_leadership                         347 Bajos (<41.3) y altos (>87.7)            27.3–41.3 (bajos) y 87.7–97.7 (altos)    CASO LEGÍTIMO        Los 201 perfiles bajos (<41.3) son candidatos con orientación operativa sin perfil de liderazgo — válidos en la plantilla. Los 146 con score alto (>87.7) son candidatos ejecutivos potenciales. Ninguno está fuera de escala.
  leadership_vision                        163 Solo bajos (<22.5 pts)                   1–22 puntos                              REQUIERE REVISIÓN    163 registros con visión de liderazgo entre 1 y 22 puntos (escala 0–100). Aunque están dentro del rango válido, valores tan bajos podrían indicar evaluaciones no completadas o perfiles ingresados en blanco. Acción: cruzar con 'profile_visibility' y verificar si tienen score_overall > 0.
  leadership_influence                     127 Solo bajos (<22.5 pts)                   4–22 puntos                              REQUIERE REVISIÓN    Mismo patrón que leadership_vision. 127 registros con influencia de liderazgo extremadamente baja. Acción: verificar si coinciden con los mismos 163 de leadership_vision para determinar si son perfiles incompletos.
  tenure_sigma_calculated                  495 Superiores al LS (23.1 años)             22.6–25.7 años                           CASO LEGÍTIMO        494 empleados con más de 22 años en Sigma — representan el grupo fundador de la empresa (Sigma lleva ~25 años en operación). Son los empleados con mayor conocimiento institucional y, paradójicamente, mayor riesgo de retiro.

6. Documentar qué variables presentan mayor variabilidad y qué implicancias tienen para el análisis.

In [181]:
# Se crea un diccionario para clasificar la interpretación de las variables con mayor variabilidad (CV)
CLASIFICACION_CV = {
    "monthly_salary_mxn":{
        "cv_high": results["monthly_salary_mxn"]["cv"],
        "cv_classification": results["monthly_salary_mxn"]["cv_classification"],
        "cv_interpretation": ("Alta variabilidad por la mezcla de niveles y países"
            "N1–N5 y posiciones con y sin comisiones variables."),
        "cv_implication": ("Cualquier análisis de equidad salarial debe segmentarse por "
            "nivel (N1–N5) + país (México / Europa / USA / Latam)"),
    },
    "monthly_salary_usd":{
        "cv_high": results["monthly_salary_usd"]["cv"],
        "cv_classification": results["monthly_salary_usd"]["cv_classification"],
        "cv_interpretation": ("Alta variabilidad por la mezcla de niveles "
            "N1–N5 y posiciones con y sin comisiones variables."),
        "cv_implication": ("Cualquier análisis de equidad salarial debe segmentarse por "
            "nivel (N1–N5) + país (México / Europa / USA / Latam)"),
    },
    "bonuses_original":{
        "cv_high": results["bonuses_original"]["cv"],
        "cv_classification": results["bonuses_original"]["cv_classification"],
        "cv_interpretation": ("Mayor variabilidad del dataset. "
            "Los bonos dependen de nivel y tipo de posición (ventas vs. staff)."),
        "cv_implication": ("No comparar bonos entre áreas sin segmentar por nivel. "
            "No usar la media como referencia; usar la mediana por segmento."),
    },
    "tenure_sigma_calculated":{
        "cv_high": results["tenure_sigma_calculated"]["cv"],
        "cv_classification": results["tenure_sigma_calculated"]["cv_classification"],
        "cv_interpretation": ("La variable más heterogénea de demographics. "
            "Coexisten empleados de meses con empleados fundadores (>22 años)."),
        "cv_implication": ("Usar la mediana (7.2 años) sobre la media (8.2 años) para análisis de antigüedad."),
    },
}

# Variables con mayor variabilidad (CV) y su interpretación
print(f"\n  {'Variable':<25} {'Coeficiente de variación':>18} {'Clasificacion':>15} {'Interpretación':>100} {'Implicación':>150}")
# Se imprime una línea divisoria para la tabla
print(f"  {'─'*25} {'─'*18} {'─'*18} {'─'*100} {'─'*150}")
# Se imprime cada variable con su coeficiente de variación y su interpretación
for name, r in CLASIFICACION_CV.items():
    print(f"  {name:<25} {r['cv_high']:.2f}%{'':>18} {r['cv_classification']:<15} {str(r['cv_interpretation']):<100} {str(r['cv_implication']):<150}")

  Variable                  Coeficiente de variación   Clasificacion                                                                                       Interpretación                                                                                                                                            Implicación
  ───────────────────────── ────────────────── ────────────────── ──────────────────────────────────────────────────────────────────────────────────────────────────── ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
  monthly_salary_mxn        89.88%                   Alta (>50%)     Alta variabilidad por la mezcla de niveles y paísesN1–N5 y posiciones con y sin comisiones variables. Cualquier análisis de equidad salarial debe segmentarse por nivel (N1–N5) + país (México / Europa / USA / Latam)
  monthly_salary_usd        89.88%                   Alta (>50%)     Alta variabilidad por la mezcla de niveles N1–N5 y posiciones con y sin comisiones variables.        Cualquier análisis de equidad salarial debe segmentarse por nivel (N1–N5) + país (México / Europa / USA / Latam)
  bonuses_original          94.68%                   Alta (>50%)     Mayor variabilidad del dataset. Los bonos dependen de nivel y tipo de posición (ventas vs. staff).   No comparar bonos entre áreas sin segmentar por nivel. No usar la media como referencia; usar la mediana por segmento.
  tenure_sigma_calculated   60.51%                   Alta (>50%)     La variable más heterogénea de demographics. Coexisten empleados de meses con empleados fundadores (>22 años). Usar la mediana (7.2 años) sobre la media (8.2 años) para análisis de antigüedad.