## Analisis de base de datos sintetica generada a partir del contexto de la empresa Sigma Foods (2026)

In [1]:
import pandas as pd

## Cargar 5 CSVs con la información de los candidatos

In [2]:
df_candidate = pd.read_csv("candidate_profile.csv",encoding='utf-8-sig')
df_dictionary = pd.read_csv("data_dictionary.csv",encoding='utf-8-sig')
df_demographics = pd.read_csv("demographics.csv",encoding='utf-8-sig')
df_plantilla = pd.read_csv("plantilla_global.csv",encoding='utf-8-sig')
df_succession = pd.read_csv("succession.csv",encoding='utf-8-sig')

df_candidate.info()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 60 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Employee ID                     50000 non-null  str
 1   Full Name                       50000 non-null  str
 2   Second Surname                  50000 non-null  str
 3   Optional Phone                  50000 non-null  int64
 4   Postal Code                     50000 non-null  int64
 5   Country                         50000 non-null  str
 6   State                           50000 non-null  str
 7   Municipality                    50000 non-null  str
 8   Date of Birth                   50000 non-null  str
 9   Nationality                     50000 non-null  str
 10  Civil Status                    50000 non-null  str
 11  Native Language                 50000 non-null  str
 12  Profile Visibility              50000 non-null  str
 13  Relocation Availability         50000 non-null  str
 14  Education_Degree_1              50000 non-null  str
 15  Education_Institution_1         50000 non-null  str
 16  Education_Field_1               50000 non-null  str
 17  Education_Year_1                50000 non-null  int64
 18  Education_Degree_2              50000 non-null  str
 19  Education_Institution_2         50000 non-null  str
 20  Education_Field_2               50000 non-null  str
 21  Education_Year_2                50000 non-null  int64
 22  PrevJob_Company_1               50000 non-null  str
 23  PrevJob_Title_1                 50000 non-null  str
 24  PrevJob_Start_1                 50000 non-null  str
 25  PrevJob_End_1                   50000 non-null  str
 26  PrevJob_Company_2               50000 non-null  str
 27  PrevJob_Title_2                 50000 non-null  str
 28  PrevJob_Start_2                 50000 non-null  str
 29  PrevJob_End_2                   50000 non-null  str
 30  Area_of_Interest_1              50000 non-null  str
 31  Area_of_Interest_2              50000 non-null  str
 32  Certification_1                 50000 non-null  str
 33  Certification_Year_1            50000 non-null  int64
 34  Certification_2                 50000 non-null  str
 35  Certification_Year_2            50000 non-null  int64
 36  Language_1                      50000 non-null  str
 37  Language_1_Level                50000 non-null  str
 38  Language_2                      50000 non-null  str
 39  Language_2_Level                50000 non-null  str
 40  Course_1                        50000 non-null  str
 41  Course_Year_1                   50000 non-null  int64
 42  Course_2                        50000 non-null  str
 43  Course_Year_2                   50000 non-null  int64
 44  Leadership_Vision               50000 non-null  int64
 45  Leadership_Influence            50000 non-null  int64
 46  Leadership_Decision_Making      50000 non-null  int64
 47  Functional_Execution            50000 non-null  int64
 48  Functional_Innovation           50000 non-null  int64
 49  Functional_Results_Orientation  50000 non-null  int64
 50  Cultural_Collaboration          50000 non-null  int64
 51  Cultural_Integrity              50000 non-null  int64
 52  Cultural_Customer_Focus         50000 non-null  int64
 53  Communication                   50000 non-null  int64
 54  Adaptability                    50000 non-null  int64
 55  Learning_Agility                50000 non-null  int64
 56  Score_Liderazgo                 50000 non-null  float64
 57  Score_Funcional                 50000 non-null  float64
 58  Score_Cultural                  50000 non-null  float64
 59  Score_General                   50000 non-null  float64
dtypes: float64(4), int64(20), str(36)
memory usage: 22.9 MB

In [3]:
df_candidate.dtypes

Employee ID                           str
Full Name                             str
Second Surname                        str
Optional Phone                      int64
Postal Code                         int64
Country                               str
State                                 str
Municipality                          str
Date of Birth                         str
Nationality                           str
Civil Status                          str
Native Language                       str
Profile Visibility                    str
Relocation Availability               str
Education_Degree_1                    str
Education_Institution_1               str
Education_Field_1                     str
Education_Year_1                    int64
Education_Degree_2                    str
Education_Institution_2               str
Education_Field_2                     str
Education_Year_2                    int64
PrevJob_Company_1                     str
PrevJob_Title_1                       str
PrevJob_Start_1                       str
PrevJob_End_1                         str
PrevJob_Company_2                     str
PrevJob_Title_2                       str
PrevJob_Start_2                       str
PrevJob_End_2                         str
Area_of_Interest_1                    str
Area_of_Interest_2                    str
Certification_1                       str
Certification_Year_1                int64
Certification_2                       str
Certification_Year_2                int64
Language_1                            str
Language_1_Level                      str
Language_2                            str
Language_2_Level                      str
Course_1                              str
Course_Year_1                       int64
Course_2                              str
Course_Year_2                       int64
Leadership_Vision                   int64
Leadership_Influence                int64
Leadership_Decision_Making          int64
Functional_Execution                int64
Functional_Innovation               int64
Functional_Results_Orientation      int64
Cultural_Collaboration              int64
Cultural_Integrity                  int64
Cultural_Customer_Focus             int64
Communication                       int64
Adaptability                        int64
Learning_Agility                    int64
Score_Liderazgo                   float64
Score_Funcional                   float64
Score_Cultural                    float64
Score_General                     float64
dtype: object

## Se verificaron las columnas y los nombres de indice para cada dataset

In [4]:
#Cambiamos nombre de columna "NIP -> Employee ID" para homogenizar indices
df_plantilla = df_plantilla.rename(columns={'NIP': 'Employee ID'})

#Observamos las columnas y conteo su respectivo conteo
print("Columnas de df_plantilla:")
print(list(df_plantilla.columns))
print("Columnas:",len(df_plantilla.columns))
print()
print("Columnas de df_demographics:")
print(list(df_demographics.columns))
print("Columnas:",len(df_demographics.columns))
print()
print("Columnas de df_candidate:")
print(list(df_candidate.columns))
print("Columnas:",len(df_candidate.columns))

#Después aplicas el index para cada csv
df_plantilla = df_plantilla.set_index('Employee ID')
df_demographics = df_demographics.set_index('Employee ID')
df_candidate = df_candidate.set_index('Employee ID')

print()
#Comprobamos los indices para cada csv
print()
print("Índice de df_plantilla:", df_plantilla.index.name)
print("Índice de df_demographics:", df_demographics.index.name)
print("Índice de df_candidate:", df_candidate.index.name)

Columnas de df_plantilla:
['Employee ID', 'NOMBRE', 'GENERO', 'F.NACIMIENTO', 'F.I.ALFA', 'F.I.SIGMA', 'DESCRIP. DIRECCION', 'DESCRIP. GERENCIA', 'DESCRIP. AREA', 'DESCRIP. DEPARTAMENTO', 'DESCRIP. SITE', 'Country', 'NIVEL', 'IPE', 'SEGMENTO P', 'EXECUTIVE', 'DIVISION', 'DESCRIP. FUNCION', 'SUBTIPO', 'GRUPO', 'SUELDO SAP', 'SDO MENSUALIZAD', 'MONED', 'TIPO CAM', 'SDO PESOS MXN', 'Sueldo USD', 'BONOS Y COM ORI', 'SDO BYC MXN', 'POSICI']
Columnas: 29

Columnas de df_demographics:
['Employee ID', 'Employee Name', 'Gender', 'Date of Birth', 'Type of Employee', 'Employee Position Type', 'Date of Entry to Alfa', 'Date of Entry to Sigma', 'Headcount', 'Age', 'Tenure (Years) Alfa', 'Tenure (Years) Sigma', 'Age Band', 'Tenure Band']
Columnas: 14

Columnas de df_candidate:
['Employee ID', 'Full Name', 'Second Surname', 'Optional Phone', 'Postal Code', 'Country', 'State', 'Municipality', 'Date of Birth', 'Nationality', 'Civil Status', 'Native Language', 'Profile Visibility', 'Relocation Availability', 'Education_Degree_1', 'Education_Institution_1', 'Education_Field_1', 'Education_Year_1', 'Education_Degree_2', 'Education_Institution_2', 'Education_Field_2', 'Education_Year_2', 'PrevJob_Company_1', 'PrevJob_Title_1', 'PrevJob_Start_1', 'PrevJob_End_1', 'PrevJob_Company_2', 'PrevJob_Title_2', 'PrevJob_Start_2', 'PrevJob_End_2', 'Area_of_Interest_1', 'Area_of_Interest_2', 'Certification_1', 'Certification_Year_1', 'Certification_2', 'Certification_Year_2', 'Language_1', 'Language_1_Level', 'Language_2', 'Language_2_Level', 'Course_1', 'Course_Year_1', 'Course_2', 'Course_Year_2', 'Leadership_Vision', 'Leadership_Influence', 'Leadership_Decision_Making', 'Functional_Execution', 'Functional_Innovation', 'Functional_Results_Orientation', 'Cultural_Collaboration', 'Cultural_Integrity', 'Cultural_Customer_Focus', 'Communication', 'Adaptability', 'Learning_Agility', 'Score_Liderazgo', 'Score_Funcional', 'Score_Cultural', 'Score_General']
Columnas: 60


Índice de df_plantilla: Employee ID
Índice de df_demographics: Employee ID
Índice de df_candidate: Employee ID

In [5]:
print("Índice de df_succession:", df_succession.index.name)
print("Primeras filas:")
df_succession.head(3)

Índice de df_succession: None
Primeras filas:

,Position_Code,Job Title,Level,Position_Business_Unit,Incumbent_Id,Incumbent Full Name,Incumbent_OU,Incumbent_Date_Of_Birth,Edad,Nominee_User_ID,Full Name Sucesor,Nominee_Gender,Nominee_Date_of_Birth,Nominee_Position_Title,Nominee_Position_Code,Nominee_Business_Unit,Nomination_Readiness,Nomination_Date,Nominator_User_ID
0,POS13178,Manager Operaciones,N1,Dirección de Operaciones,NIP119205,Elena Flores,Área CDMX,1983-10-25,41,NIP144127,Óscar Luna,M,1973-12-22,Analyst Logística,POS28384,Dirección de Operaciones,Short Term,2025-07-26,NIP144680
1,POS12049,Manager Logística,N1,Dirección de RH,NIP106565,Ana Chavez,Área Centro,1992-02-18,33,NIP122110,Cristina Ramos,F,1998-06-29,Analyst Ventas,POS27005,Dirección Legal,Long Term,2025-01-19,NIP104710
2,POS12956,Manager Ventas,N2,Dirección de Marketing,NIP109751,Enrique Ortiz,Área Centro,1990-07-19,34,NIP103274,Héctor Villalobos,M,1992-11-10,Analyst Logística,POS21161,Dirección de Tecnología,Short Term,2024-07-18,NIP106109

 Se generara un indice significativo para el archivo "succession.csv" dado a que los NIP que funcionaban como identificadores únicos en el resto de archivos csv, en este en particular se repiten más de una ocasión debido a que un empleado puede ser adecuado para multiples vacantes

In [6]:
# Paso 1 — Crear la columna Nomination_ID al inicio del DataFrame
df_succession.insert(0, 'Nomination ID', range(1, len(df_succession) + 1))

# Paso 2 — Establecerla como índice
df_succession = df_succession.set_index('Nomination ID')

# Paso 3 — Verificar resultado
print(f" Succession → índice: {df_succession.index.name}")
print(f" Rango: {df_succession.index.min()} al {df_succession.index.max()}")
df_succession.sample(3)

 Succession → índice: Nomination ID
 Rango: 1 al 38200

,Position_Code,Job Title,Level,Position_Business_Unit,Incumbent_Id,Incumbent Full Name,Incumbent_OU,Incumbent_Date_Of_Birth,Edad,Nominee_User_ID,Full Name Sucesor,Nominee_Gender,Nominee_Date_of_Birth,Nominee_Position_Title,Nominee_Position_Code,Nominee_Business_Unit,Nomination_Readiness,Nomination_Date,Nominator_User_ID
Nomination ID,,,,,,,,,,,,,,,,,,,
13342,POS18147,Manager Tecnología,N2,Dirección de Operaciones,NIP104123,Norma Rodríguez,Área Norte,1968-08-29,56,NIP141695,Teresa Flores,F,2000-02-27,Analyst Ventas,POS20903,Dirección de Operaciones,Right Now,2025-10-22,NIP148012
6367,POS10761,Manager Marketing,N3,Dirección de RH,NIP114090,Claudia Herrera,Área Sur,1997-08-15,27,NIP124882,Silvia Domínguez,F,1977-12-17,Analyst Legal,POS29487,Dirección de RH,Short Term,2024-01-14,NIP123483
5837,POS10838,Manager Legal,N1,Dirección Legal,NIP124646,Fernando Flores,Área Norte,2000-11-02,24,NIP120838,Esperanza Romero,F,1997-05-24,Analyst Recursos Humanos,POS27672,Dirección Legal,Short Term,2025-04-10,NIP133852

## Seleccionar subconjuntos para verificar si los datos de los empleados tienen sentido

In [7]:
#Selecciona un empleado específico por su Employee ID y solo las columnas que nos interesan para el proyecto

df_plantilla.loc['NIP100018',['NOMBRE', 'Country', 'DIVISION', 'SEGMENTO P', 'MONED', 'SDO MENSUALIZAD']]

NOMBRE             Patricia Martínez
Country                       México
DIVISION                 Corporativo
SEGMENTO P                DIRECTORES
MONED                            MXN
SDO MENSUALIZAD             24118.83
Name: NIP100018, dtype: object

In [8]:
# Filas del 10 al 14, primeras 5 columnas
df_demographics.iloc[10:15, 0:5]

,Employee Name,Gender,Date of Birth,Type of Employee,Employee Position Type
Employee ID,,,,,
NIP100011,Patricia Rivera,Female,1980-06-20,Administrator,Contract
NIP100012,Walter Rodríguez,Male,1983-12-08,Operator,Contract
NIP100013,Finn Becker,Male,1996-06-25,Operator,Permanent
NIP100014,Miguel García,Male,1985-01-07,Administrator,Contract
NIP100015,Ricardo Sánchez,Male,1969-06-09,Operator,Temporary

In [9]:
# PROPÓSITO: Identificar candidatos con alto potencial de liderazgo para el proceso de sucesión ejecutiva —> caso de uso directo del proyecto

df_candidate[df_candidate['Score_General'] > 80][
    ['Full Name', 'Country', 'Score_Liderazgo', 'Score_Funcional', 'Score_Cultural', 'Score_General']
].head(10)

,Full Name,Country,Score_Liderazgo,Score_Funcional,Score_Cultural,Score_General
Employee ID,,,,,,
NIP102815,Manuel Flores,México,81.7,82.0,85.0,80.6
NIP114132,Jorge Rodríguez,México,87.7,86.0,75.0,82.1
NIP114496,Marcela Rivera,México,80.3,76.7,86.3,81.4
NIP119312,Manuel Sánchez,México,76.7,81.7,86.3,80.9
NIP121860,Alejandra Rivera,México,92.0,90.7,64.3,80.7
NIP127327,Gabriel Ortiz,México,84.3,86.7,76.0,80.1

## Estandarización de nombres en las 4 Tablas:

## Plantilla Global

In [10]:
df_plantilla.index.name = 'employee_id'

df_plantilla = df_plantilla.rename(columns={
    'NOMBRE'              : 'full_name',
    'GENERO'              : 'gender',
    'F.NACIMIENTO'        : 'date_of_birth',
    'F.I.ALFA'            : 'date_of_entry_alfa',
    'F.I.SIGMA'           : 'date_of_entry_sigma',
    'DESCRIP. DIRECCION'  : 'direction',
    'DESCRIP. GERENCIA'   : 'management',
    'DESCRIP. AREA'       : 'area',
    'DESCRIP. DEPARTAMENTO': 'department',
    'DESCRIP. SITE'       : 'site',
    'Country'             : 'country',
    'NIVEL'               : 'level',
    'IPE'                 : 'ipe',
    'SEGMENTO P'          : 'segment',
    'EXECUTIVE'           : 'is_executive',
    'DIVISION'            : 'division',
    'DESCRIP. FUNCION'    : 'job_function',
    'SUBTIPO'             : 'contract_type',
    'GRUPO'               : 'employee_group',
    'SUELDO SAP'          : 'salary_sap',
    'SDO MENSUALIZAD'     : 'monthly_salary',
    'MONED'               : 'currency',
    'TIPO CAM'            : 'exchange_rate',
    'SDO PESOS MXN'       : 'monthly_salary_mxn',
    'Sueldo USD'          : 'monthly_salary_usd',
    'BONOS Y COM ORI'     : 'bonuses_original',
    'SDO BYC MXN'         : 'total_compensation_mxn',
    'POSICI'              : 'comp_ratio',
})

print('Plantilla Global estandarizada')
print(f'Columnas finales: {list(df_plantilla.columns)}')

Plantilla Global estandarizada
Columnas finales: ['full_name', 'gender', 'date_of_birth', 'date_of_entry_alfa', 'date_of_entry_sigma', 'direction', 'management', 'area', 'department', 'site', 'country', 'level', 'ipe', 'segment', 'is_executive', 'division', 'job_function', 'contract_type', 'employee_group', 'salary_sap', 'monthly_salary', 'currency', 'exchange_rate', 'monthly_salary_mxn', 'monthly_salary_usd', 'bonuses_original', 'total_compensation_mxn', 'comp_ratio']

## Demographics

In [11]:
df_demographics.index.name = 'employee_id'

df_demographics = df_demographics.rename(columns={
    'Employee Name'         : 'full_name',
    'Gender'                : 'gender',
    'Date of Birth'         : 'date_of_birth',
    'Type of Employee'      : 'employee_type',
    'Employee Position Type': 'position_type',
    'Date of Entry to Alfa' : 'date_of_entry_alfa',
    'Date of Entry to Sigma': 'date_of_entry_sigma',
    'Headcount'             : 'headcount',
    'Age'                   : 'age',
    'Tenure (Years) Alfa'   : 'tenure_alfa_years',
    'Tenure (Years) Sigma'  : 'tenure_sigma_years',
    'Age Band'              : 'age_band',
    'Tenure Band'           : 'tenure_band',
})

print('Demographics estandarizado')
print(f'Columnas finales: {list(df_demographics.columns)}')

Demographics estandarizado
Columnas finales: ['full_name', 'gender', 'date_of_birth', 'employee_type', 'position_type', 'date_of_entry_alfa', 'date_of_entry_sigma', 'headcount', 'age', 'tenure_alfa_years', 'tenure_sigma_years', 'age_band', 'tenure_band']

## Candidate Profile

In [12]:
df_candidate.index.name = 'employee_id'

df_candidate = df_candidate.rename(columns={
    'Full Name'                    : 'full_name',
    'Second Surname'               : 'second_surname',
    'Optional Phone'               : 'phone',
    'Postal Code'                  : 'postal_code',
    'Country'                      : 'country',
    'State'                        : 'state',
    'Municipality'                 : 'municipality',
    'Date of Birth'                : 'date_of_birth',
    'Nationality'                  : 'nationality',
    'Civil Status'                 : 'civil_status',
    'Native Language'              : 'native_language',
    'Profile Visibility'           : 'profile_visibility',
    'Relocation Availability'      : 'relocation_available',
    'Education_Degree_1'           : 'education_degree_1',
    'Education_Institution_1'      : 'education_institution_1',
    'Education_Field_1'            : 'education_field_1',
    'Education_Year_1'             : 'education_year_1',
    'Education_Degree_2'           : 'education_degree_2',
    'Education_Institution_2'      : 'education_institution_2',
    'Education_Field_2'            : 'education_field_2',
    'Education_Year_2'             : 'education_year_2',
    'PrevJob_Company_1'            : 'prev_company_1',
    'PrevJob_Title_1'              : 'prev_title_1',
    'PrevJob_Start_1'              : 'prev_start_1',
    'PrevJob_End_1'                : 'prev_end_1',
    'PrevJob_Company_2'            : 'prev_company_2',
    'PrevJob_Title_2'              : 'prev_title_2',
    'PrevJob_Start_2'              : 'prev_start_2',
    'PrevJob_End_2'                : 'prev_end_2',
    'Area_of_Interest_1'           : 'interest_area_1',
    'Area_of_Interest_2'           : 'interest_area_2',
    'Certification_1'              : 'certification_1',
    'Certification_Year_1'         : 'certification_year_1',
    'Certification_2'              : 'certification_2',
    'Certification_Year_2'         : 'certification_year_2',
    'Language_1'                   : 'language_1',
    'Language_1_Level'             : 'language_1_level',
    'Language_2'                   : 'language_2',
    'Language_2_Level'             : 'language_2_level',
    'Course_1'                     : 'course_1',
    'Course_Year_1'                : 'course_year_1',
    'Course_2'                     : 'course_2',
    'Course_Year_2'                : 'course_year_2',
    'Leadership_Vision'            : 'leadership_vision',
    'Leadership_Influence'         : 'leadership_influence',
    'Leadership_Decision_Making'   : 'leadership_decision_making',
    'Functional_Execution'         : 'functional_execution',
    'Functional_Innovation'        : 'functional_innovation',
    'Functional_Results_Orientation': 'functional_results_orientation',
    'Cultural_Collaboration'       : 'cultural_collaboration',
    'Cultural_Integrity'           : 'cultural_integrity',
    'Cultural_Customer_Focus'      : 'cultural_customer_focus',
    'Communication'                : 'communication',
    'Adaptability'                 : 'adaptability',
    'Learning_Agility'             : 'learning_agility',
    'Score_Liderazgo'              : 'score_leadership',
    'Score_Funcional'              : 'score_functional',
    'Score_Cultural'               : 'score_cultural',
    'Score_General'                : 'score_overall',
})

print('Candidate Profile estandarizado')
print(f'Columnas finales: {list(df_candidate.columns)}')

Candidate Profile estandarizado
Columnas finales: ['full_name', 'second_surname', 'phone', 'postal_code', 'country', 'state', 'municipality', 'date_of_birth', 'nationality', 'civil_status', 'native_language', 'profile_visibility', 'relocation_available', 'education_degree_1', 'education_institution_1', 'education_field_1', 'education_year_1', 'education_degree_2', 'education_institution_2', 'education_field_2', 'education_year_2', 'prev_company_1', 'prev_title_1', 'prev_start_1', 'prev_end_1', 'prev_company_2', 'prev_title_2', 'prev_start_2', 'prev_end_2', 'interest_area_1', 'interest_area_2', 'certification_1', 'certification_year_1', 'certification_2', 'certification_year_2', 'language_1', 'language_1_level', 'language_2', 'language_2_level', 'course_1', 'course_year_1', 'course_2', 'course_year_2', 'leadership_vision', 'leadership_influence', 'leadership_decision_making', 'functional_execution', 'functional_innovation', 'functional_results_orientation', 'cultural_collaboration', 'cultural_integrity', 'cultural_customer_focus', 'communication', 'adaptability', 'learning_agility', 'score_leadership', 'score_functional', 'score_cultural', 'score_overall']

## Succession

In [13]:
df_succession.index.name = 'nomination_id'

df_succession = df_succession.rename(columns={
    'Position_Code'          : 'position_code',
    'Job Title'              : 'job_title',
    'Level'                  : 'level',
    'Position_Business_Unit' : 'business_unit',
    'Incumbent_Id'           : 'incumbent_id',
    'Incumbent Full Name'    : 'incumbent_name',
    'Incumbent_OU'           : 'incumbent_ou',
    'Incumbent_Date_Of_Birth': 'incumbent_dob',
    'Edad'                   : 'incumbent_age',
    'Nominee_User_ID'        : 'nominee_id',
    'Full Name Sucesor'      : 'nominee_name',
    'Nominee_Gender'         : 'nominee_gender',
    'Nominee_Date_of_Birth'  : 'nominee_dob',
    'Nominee_Position_Title' : 'nominee_position_title',
    'Nominee_Position_Code'  : 'nominee_position_code',
    'Nominee_Business_Unit'  : 'nominee_business_unit',
    'Nomination_Readiness'   : 'readiness',
    'Nomination_Date'        : 'nomination_date',
    'Nominator_User_ID'      : 'nominator_id',
})

print('Succession estandarizado')
print(f'Columnas finales: {list(df_succession.columns)}')

Succession estandarizado
Columnas finales: ['position_code', 'job_title', 'level', 'business_unit', 'incumbent_id', 'incumbent_name', 'incumbent_ou', 'incumbent_dob', 'incumbent_age', 'nominee_id', 'nominee_name', 'nominee_gender', 'nominee_dob', 'nominee_position_title', 'nominee_position_code', 'nominee_business_unit', 'readiness', 'nomination_date', 'nominator_id']

## Información de la Plantilla Global de Sigma Foods (Datos sintéticos)

In [14]:
df_plantilla.info()

<class 'pandas.DataFrame'>
Index: 50000 entries, NIP100001 to NIP150000
Data columns (total 28 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   full_name               50000 non-null  str
 1   gender                  50000 non-null  str
 2   date_of_birth           50000 non-null  str
 3   date_of_entry_alfa      50000 non-null  str
 4   date_of_entry_sigma     50000 non-null  str
 5   direction               50000 non-null  str
 6   management              50000 non-null  str
 7   area                    50000 non-null  str
 8   department              50000 non-null  str
 9   site                    50000 non-null  str
 10  country                 50000 non-null  str
 11  level                   50000 non-null  str
 12  ipe                     50000 non-null  int64
 13  segment                 50000 non-null  str
 14  is_executive            50000 non-null  str
 15  division                50000 non-null  str
 16  job_function            50000 non-null  str
 17  contract_type           50000 non-null  str
 18  employee_group          50000 non-null  str
 19  salary_sap              50000 non-null  float64
 20  monthly_salary          50000 non-null  float64
 21  currency                50000 non-null  str
 22  exchange_rate           50000 non-null  float64
 23  monthly_salary_mxn      50000 non-null  float64
 24  monthly_salary_usd      50000 non-null  float64
 25  bonuses_original        50000 non-null  float64
 26  total_compensation_mxn  50000 non-null  float64
 27  comp_ratio              50000 non-null  float64
dtypes: float64(8), int64(1), str(19)
memory usage: 12.1+ MB

## Conteo de empleados por región

In [15]:
# Distribución geográfica de empleados por región
distribucion_geografica = df_plantilla.groupby('country').agg(
    total_empleados=('full_name', 'count'),
).reset_index()

# Agregar porcentaje
distribucion_geografica['porcentaje'] = (
    distribucion_geografica['total_empleados'] / 
    distribucion_geografica['total_empleados'].sum() * 100
).round(1).astype(str) + '%'

# Ordenar de mayor a menor
distribucion_geografica = distribucion_geografica.sort_values(
    'total_empleados', ascending=False
).reset_index(drop=True)

# Renombrar columnas para presentación
distribucion_geografica.columns = ['Región', 'Total Empleados', '% del Total']

print('Distribución geográfica del dataset sintético')
print(f'Total registros: {distribucion_geografica["Total Empleados"].sum():,}')
print()
distribucion_geografica

Distribución geográfica del dataset sintético
Total registros: 50,000

   Región  Total Empleados % del Total
0  México            31081       62.2%
1  Europa            11462       22.9%
2     USA             4487        9.0%
3   Latam             2970        5.9%

In [16]:
df_succession.info()

<class 'pandas.DataFrame'>
RangeIndex: 38200 entries, 1 to 38200
Data columns (total 19 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   position_code           38200 non-null  str
 1   job_title               38200 non-null  str
 2   level                   38200 non-null  str
 3   business_unit           38200 non-null  str
 4   incumbent_id            38200 non-null  str
 5   incumbent_name          38200 non-null  str
 6   incumbent_ou            38200 non-null  str
 7   incumbent_dob           38200 non-null  str
 8   incumbent_age           38200 non-null  int64
 9   nominee_id              38200 non-null  str
 10  nominee_name            38200 non-null  str
 11  nominee_gender          38200 non-null  str
 12  nominee_dob             38200 non-null  str
 13  nominee_position_title  38200 non-null  str
 14  nominee_position_code   38200 non-null  str
 15  nominee_business_unit   38200 non-null  str
 16  readiness               38200 non-null  str
 17  nomination_date         38200 non-null  str
 18  nominator_id            38200 non-null  str
dtypes: int64(1), str(18)
memory usage: 5.5 MB

## Actividad 5 - Corrección de tipos y datos temporales

1. Revisar el tipo de dato de cada columna e identificar las interpretadas de manera incorrecta

In [17]:
#Revisión de cada una de las tablas de datos:
print('── Plantilla Global ──')
print(df_plantilla.dtypes.to_string())

── Plantilla Global ──
full_name                     str
gender                        str
date_of_birth                 str
date_of_entry_alfa            str
date_of_entry_sigma           str
direction                     str
management                    str
area                          str
department                    str
site                          str
country                       str
level                         str
ipe                         int64
segment                       str
is_executive                  str
division                      str
job_function                  str
contract_type                 str
employee_group                str
salary_sap                float64
monthly_salary            float64
currency                      str
exchange_rate             float64
monthly_salary_mxn        float64
monthly_salary_usd        float64
bonuses_original          float64
total_compensation_mxn    float64
comp_ratio                float64

In [18]:
print('── Demographics ──')
print(df_demographics.dtypes.to_string())

── Demographics ──
full_name                  str
gender                     str
date_of_birth              str
employee_type              str
position_type              str
date_of_entry_alfa         str
date_of_entry_sigma        str
headcount                int64
age                      int64
tenure_alfa_years      float64
tenure_sigma_years     float64
age_band                   str
tenure_band                str

In [19]:
print('── Candidate Profile ──')
print(df_candidate.dtypes.to_string())

── Candidate Profile ──
full_name                             str
second_surname                        str
phone                               int64
postal_code                         int64
country                               str
state                                 str
municipality                          str
date_of_birth                         str
nationality                           str
civil_status                          str
native_language                       str
profile_visibility                    str
relocation_available                  str
education_degree_1                    str
education_institution_1               str
education_field_1                     str
education_year_1                    int64
education_degree_2                    str
education_institution_2               str
education_field_2                     str
education_year_2                    int64
prev_company_1                        str
prev_title_1                          str
prev_start_1                          str
prev_end_1                            str
prev_company_2                        str
prev_title_2                          str
prev_start_2                          str
prev_end_2                            str
interest_area_1                       str
interest_area_2                       str
certification_1                       str
certification_year_1                int64
certification_2                       str
certification_year_2                int64
language_1                            str
language_1_level                      str
language_2                            str
language_2_level                      str
course_1                              str
course_year_1                       int64
course_2                              str
course_year_2                       int64
leadership_vision                   int64
leadership_influence                int64
leadership_decision_making          int64
functional_execution                int64
functional_innovation               int64
functional_results_orientation      int64
cultural_collaboration              int64
cultural_integrity                  int64
cultural_customer_focus             int64
communication                       int64
adaptability                        int64
learning_agility                    int64
score_leadership                  float64
score_functional                  float64
score_cultural                    float64
score_overall                     float64

In [20]:
print('── Succession ──')
print(df_succession.dtypes.to_string())

── Succession ──
position_code               str
job_title                   str
level                       str
business_unit               str
incumbent_id                str
incumbent_name              str
incumbent_ou                str
incumbent_dob               str
incumbent_age             int64
nominee_id                  str
nominee_name                str
nominee_gender              str
nominee_dob                 str
nominee_position_title      str
nominee_position_code       str
nominee_business_unit       str
readiness                   str
nomination_date             str
nominator_id                str

-Algunas fechas son marcadas como tipo str, eso puede afectar en los calculos de antiguedad de los empleados, deben modificarsse a 'datetime64' 

-los telefonos deben ser identificadores para evitar operaciones aritmeticas con ellos, deben cambiarse a tipo 'str'

In [21]:
#CAmbiar tipo de phone y postal_code por 'str' para la tabla de candidates 

df_candidate['phone'] = df_candidate['phone'].astype(str)
df_candidate['postal_code'] = df_candidate['postal_code'].astype(str) 

#Comprobar los cambios hechos en el tipo de datos
print('─'*12, 'Candidate Profile', '─'*12)
print(df_candidate.dtypes.to_string())

──────────── Candidate Profile ────────────
full_name                             str
second_surname                        str
phone                                 str
postal_code                           str
country                               str
state                                 str
municipality                          str
date_of_birth                         str
nationality                           str
civil_status                          str
native_language                       str
profile_visibility                    str
relocation_available                  str
education_degree_1                    str
education_institution_1               str
education_field_1                     str
education_year_1                    int64
education_degree_2                    str
education_institution_2               str
education_field_2                     str
education_year_2                    int64
prev_company_1                        str
prev_title_1                          str
prev_start_1                          str
prev_end_1                            str
prev_company_2                        str
prev_title_2                          str
prev_start_2                          str
prev_end_2                            str
interest_area_1                       str
interest_area_2                       str
certification_1                       str
certification_year_1                int64
certification_2                       str
certification_year_2                int64
language_1                            str
language_1_level                      str
language_2                            str
language_2_level                      str
course_1                              str
course_year_1                       int64
course_2                              str
course_year_2                       int64
leadership_vision                   int64
leadership_influence                int64
leadership_decision_making          int64
functional_execution                int64
functional_innovation               int64
functional_results_orientation      int64
cultural_collaboration              int64
cultural_integrity                  int64
cultural_customer_focus             int64
communication                       int64
adaptability                        int64
learning_agility                    int64
score_leadership                  float64
score_functional                  float64
score_cultural                    float64
score_overall                     float64

In [22]:
print(f'   phone       → {df_candidate["phone"].dtype}')
print(f'   postal_code → {df_candidate["postal_code"].dtype}')

   phone       → str
   postal_code → str

3. Verificar el cambio de tipo para las fechas:

In [23]:
# Columnas de fecha identificadas en las 4 tablas
fechas_plantilla   = ['date_of_birth', 'date_of_entry_alfa', 'date_of_entry_sigma']
fechas_demo        = ['date_of_birth', 'date_of_entry_alfa', 'date_of_entry_sigma']
fechas_candidate   = ['date_of_birth', 'prev_start_1', 'prev_end_1',
                      'prev_start_2', 'prev_end_2']
fechas_succession  = ['nomination_date', 'incumbent_dob', 'nominee_dob']

for col in fechas_plantilla:
    df_plantilla[col] = pd.to_datetime(df_plantilla[col], errors='coerce')

for col in fechas_demo:
    df_demographics[col] = pd.to_datetime(df_demographics[col], errors='coerce')

for col in fechas_candidate:
    df_candidate[col] = pd.to_datetime(df_candidate[col], errors='coerce')

for col in fechas_succession:
    df_succession[col] = pd.to_datetime(df_succession[col], errors='coerce')

# Verificar resultado
print('— Fechas convertidas a datetime64:\n')
print('Plantilla Global:')
for col in fechas_plantilla:
    print(f'   {col} → {df_plantilla[col].dtype}')
print('\nDemographics:')
for col in fechas_demo:
    print(f'   {col} → {df_demographics[col].dtype}')
print('\nCandidate Profile:')
for col in fechas_candidate:
    print(f'   {col} → {df_candidate[col].dtype}')
print('\nSuccession:')
for col in fechas_succession:
    print(f'   {col} → {df_succession[col].dtype}')

— Fechas convertidas a datetime64:

Plantilla Global:
   date_of_birth → datetime64[us]
   date_of_entry_alfa → datetime64[us]
   date_of_entry_sigma → datetime64[us]

Demographics:
   date_of_birth → datetime64[us]
   date_of_entry_alfa → datetime64[us]
   date_of_entry_sigma → datetime64[us]

Candidate Profile:
   date_of_birth → datetime64[us]
   prev_start_1 → datetime64[us]
   prev_end_1 → datetime64[us]
   prev_start_2 → datetime64[us]
   prev_end_2 → datetime64[us]

Succession:
   nomination_date → datetime64[us]
   incumbent_dob → datetime64[us]
   nominee_dob → datetime64[us]

4. Derivar componentes temporales útiles para el análisis, como año, mes o día de la semana, cuando los datos lo permitan.

In [24]:
#Realizamos importación de libreria datetime
from datetime import date

hoy = pd.Timestamp.today()

# ── Demographics ───
# Año de ingreso a Sigma (útil para análisis de cohortes)
df_demographics['entry_sigma_year'] = df_demographics['date_of_entry_sigma'].dt.year

# Mes de ingreso (¿hay estacionalidad en contrataciones?)
df_demographics['entry_sigma_month'] = df_demographics['date_of_entry_sigma'].dt.month

# Antigüedad recalculada desde fecha real (más precisa que el campo original)
df_demographics['tenure_sigma_calculated'] = (
    (hoy - df_demographics['date_of_entry_sigma']).dt.days / 365.25
).round(2)

# Edad recalculada desde fecha real
df_demographics['age_calculated'] = (
    (hoy - df_demographics['date_of_birth']).dt.days / 365.25
).astype(int)

# ── Succession ───
# Año y mes de nominación
df_succession['nomination_year']  = df_succession['nomination_date'].dt.year
df_succession['nomination_month'] = df_succession['nomination_date'].dt.month

# Edad del incumbente calculada a.k.a. quién ostenta el la vacante a ser sedida por un candidato potencial
df_succession['incumbent_age_calculated'] = (
    (hoy - df_succession['incumbent_dob']).dt.days / 365.25
).astype(int)

print('Ejemplos de "Componentes temporales derivados":\n')
print('Demographics:')
print(df_demographics[['date_of_entry_sigma','entry_sigma_year',
                        'entry_sigma_month','tenure_sigma_calculated',
                        'age_calculated']].head(3).to_string())
print('\nSuccession:')
print(df_succession[['nomination_date','nomination_year',
                     'nomination_month','incumbent_age_calculated']].head(3).to_string())

Ejemplos de "Componentes temporales derivados":

Demographics:
            date_of_entry_sigma  entry_sigma_year  entry_sigma_month  tenure_sigma_calculated  age_calculated
employee_id
NIP100001            2015-12-28              2015                 12                    10.52              46
NIP100002            2017-02-21              2017                  2                     9.37              34
NIP100003            2021-10-07              2021                 10                     4.74              48

Succession:
              nomination_date  nomination_year  nomination_month  incumbent_age_calculated
nomination_id
1                  2025-07-26             2025                 7                        42
2                  2025-01-19             2025                 1                        34
3                  2024-07-18             2024                 7                        35

5. Crear una columna calculada relevante mediante una operación entre columnas existentes.

In [25]:
# Columna calculada a partir de los años que le faltan al incumbente para llegar a 65 años
# (edad típica de retiro ejecutivo — indica urgencia de sucesión)
df_succession['years_to_retirement'] = (
    65 - df_succession['incumbent_age_calculated']
).clip(lower=0)  # evita valores negativos si ya pasó los 65

# Clasificar urgencia de sucesión
df_succession['succession_urgency'] = pd.cut(
    df_succession['years_to_retirement'],
    bins=[-1, 3, 7, 15, 100],
    labels=['Crítica', 'Alta', 'Media', 'Baja']
)

print('Columna calculada: urgencia de sucesión\n')
print(df_succession[['incumbent_id', 'incumbent_age_calculated',
                      'years_to_retirement',
                      'succession_urgency']].sample(10).to_string())

print('\nDistribución de urgencia:')
print(df_succession['succession_urgency'].value_counts())

Columna calculada: urgencia de sucesión

              incumbent_id  incumbent_age_calculated  years_to_retirement succession_urgency
nomination_id
1950             NIP110993                        38                   27               Baja
5053             NIP127788                        49                   16               Baja
14228            NIP123650                        30                   35               Baja
24307            NIP146262                        29                   36               Baja
11596            NIP133131                        53                   12              Media
37893            NIP134325                        57                    8              Media
23606            NIP139337                        39                   26               Baja
37339            NIP119868                        36                   29               Baja
32836            NIP121807                        52                   13              Media
9864             NIP115012                        55                   10              Media

Distribución de urgencia:
succession_urgency
Baja       28301
Media       9297
Alta         602
Crítica        0
Name: count, dtype: int64

## Actividad 6

1. Seleccionar las variables numéricas más vinculadas con el desafío del proyecto.

2. Calcular la media, la mediana y la moda de cada variable.

3. Determinar qué medida representa mejor a cada variable según su comportamiento.

4. Inferir, a partir de los estadísticos disponibles, si existen indicios de simetría, sesgo o concentración de valores.

5. Identificar las variables donde la media y la mediana difieren de manera notable, y explicar qué indica esa diferencia.

6. Sintetizar los principales resultados del perfil estadístico en lenguaje de negocio.